### ISSUE TITLE
When doing MD, the SCF iteration cycle number of ABACUS is larger than QE

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#1045]
I have run the MD (NVE) by ABACUS and QE, respectively. The SCF iteration cycle of the 1st ION step is both 12, but the SCF iteration cycle number of later ION steps are larger than that in QE.

SCF iteration cycle number
------------------------------
|ION step|ABACUS|QE|
|:----:|:----:|:----:|
|1|12|12|
|2|7|3|
|3|7|4|
|4|7|4|
|5|7|4|

The INPUT and OUTPUT files:
[example.zip](https://github.com/deepmodeling/abacus-develop/files/8997040/example.zip)

**Comment by YuLiu98** [comment]
Hi, I have fixed the charge extrapolation method.

However, there is **one important point**  that the atomic positions between QE-md and ABACUS-md are different due to their velocities are different.

So, in order to check the charge extrapolation method, you should replace **source/src_pw/run_md_pw.cpp** and **source/src_pw/run_md_pw.h** with new corresponding files in the **correction.tar.gz** to keep the atomic positions consistent between QE and ABACUS.

[correction.tar.gz](https://github.com/deepmodeling/abacus-develop/files/9034077/correction.tar.gz)

**Comment by caic99** [comment]
closed by #1060

**Comment by YuLiu98** [comment]
> I have run the MD (NVE) by ABACUS and QE, respectively. The SCF iteration cycle of the 1st ION step is both 12, but the SCF iteration cycle number of later ION steps are larger than that in QE.
> 
> ## SCF iteration cycle number
> ION step	ABACUS	QE
> 1	12	12
> 2	7	3
> 3	7	4
> 4	7	4
> 5	7	4
> The INPUT and OUTPUT files: [example.zip](https://github.com/deepmodeling/abacus-develop/files/8997040/example.zip)

Hi @pxlxingliang , today I rechecked this issue using your example (commit: a619e15a39f9bdb8991883cd411efbd70cba67b2). 

However, I found a vital problem about your parameter setting: `tempw` cannot be used to determine the initial temperature unless `ion_temperature` is set to `initial`. 

Thus, the inital temperature is actually zero, while that of ABACUS is 100 Kelvin, which means that they are absolutely different..

After aligning all parameters, I found that the number of iteration steps for each ion step of ABACUS and QE is exactly the same.   

The INPUT and OUTPUT files: [test_chg_extrap.tar.gz](https://github.com/deepmodeling/abacus-develop/files/12639775/test_chg_extrap.tar.gz)
