### ISSUE TITLE
ABACUS can not read the pseudo type of "UPF version="2.1.2"

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#1281]
### Describe the bug

In the example examples/soc/pw_GaAs, the pseudopotential file 'As_ONCV_PBE-1.1.upf' is used, and the UPF version is 2.1.2.

When I running the example, ABACUS throw the error:
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                         NOTICE                           
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 
 Pseudopotential data do not match.
 CHECK IN FILE : OUT.test/

### Expected behavior

no

### To Reproduce

no

### Environment

no

### Additional Context

no

**Comment by dyzheng** [comment]
@sunliang98 please check updates in #1247

**Comment by sunliang98** [comment]
ABACUS supports the pseudopotential in  `upf`, `upf201`, `vwr`, and `blps` format, not including 'UPF 2.1.2'.
The 'As_ONCV_PBE-1.1.upf' is in the same format of 'UPF 2.0.1', so that modify `<UPF version="2.1.2">` to `<UPF version="2.0.1">` can solve the problem.
And I don't find anything about pseudopotential in 'UPF 2.1.2' format on either the website of QE or sg15 library, considering the format of this 'UPF 2.1.2' pp is the same as 'UPF 2.0.1', I guess the pseudopotential file is labeled with the wrong version number.

**Comment by pxlxingliang** [comment]
YES, maybe it is just a mistake
