### ISSUE TITLE
The convergence of structural relaxation is unstable!

### ISSUE THREAD

**Issue by sgyang345** [deepmodeling/abacus-develop#1442]
### Describe the bug

When the structure of more than 1000 atomic systems (containing more than three elements) is calculated, the initial electron steps can converge well, but then it is easy for the electron steps to not converge, resulting in the entire calculation not converging.

<img width="364" alt="QQ20221026-105515@2x" src="https://user-images.githubusercontent.com/68679106/197925264-a52da484-6cac-4186-9abd-9ff97086c750.png">

### To Reproduce

run ABACUS with 3.0.0 or lesser versions

**Comment by wenfei-li** [comment]
This problem seems to be common for very large systems where the configuration space becomes very complicated. There is no general solution for such cases, but you might try a few things:

1. set the extrapolation method to be first order: http://abacus.deepmodeling.com/en/latest/advanced/input_files/input-main.html#chg-extrap
2. make the CG steps less aggressive by adjusting the parameter relax_bfgs_init (the default is 0.5) and relax_bfgs_rmax (the default is 0.8), an introduction of the two parameters is in this part: http://abacus.deepmodeling.com/en/latest/advanced/input_files/input-main.html#geometry-relaxation
3. use BFGS algorithm
4. use FIRE, FIRE is different from CG or BFGS in that it is actually a MD algorithm. I'm not very familiar with MD but you might refer to this part of the documentation: http://abacus.deepmodeling.com/en/latest/advanced/input_files/input-main.html#molecular-dynamics
