### ISSUE TITLE
Thread-safe GlobalC::GridD for multi-threading usage

### ISSUE THREAD

**Issue by Alcanderian** [deepmodeling/abacus-develop#1555]
### Describe Current Status and Possible Solution

I am currently working on LCAO ForceStressIntegralPart OpenMP optimization.
And found there was a problem on GlobalC::GridD.Find_atom(https://github.com/deepmodeling/abacus-develop/blob/develop/source/src_lcao/FORCE_k.cpp#L700)

GlobalC::GridD is a global single instance. And its member function such as `Find_atom` and `get_adjs` will write results in its member `adj_num`, `ntype`, `natom` etc. 
It will cause write confilct in multi-threading usage. So the API is **NOT thread-safe**.

A possible solution is overload `Find_atom` and `Find_adjacent_atom` with param
`std::vector<std::tuple<int, int, ModuleBase::Vector3<int>, ModuleBase::Vector3<double>>>`
Then add a param `bool thread_safe = false` in `get_adjs`.

`get_adjs` will call the new `Find_atom` and  when `thread_safe == true`

Calling `get_adjs` in parallel loop will be enabled with this ehancement.
Further more, A thread-safe `get_adjs(const UnitCell& ucell_in, const size_t &iat)` help me to bring an efficient multi-threaded `get_adjs(const UnitCell& ucell_in)`

**Comment by dyzheng** [comment]
In MPI parallel, orbitals(mu or nu) is paralleled but not ions(iat), https://github.com/deepmodeling/abacus-develop/blob/develop/source/src_lcao/FORCE_k.cpp#L806 .

Focus on GlobalC::GridD.Find_atom(), saving neighbor lists for each atom seems not a good idea, because of when system is large and number of atoms is too many, the memory cost for saving all neighbor lists looks unacceptable. 
On the other hand, saving neighbor lists for each thread looks reasonable.

**Comment by caic99** [comment]
@Alcanderian We think your proposal is good to carry on. It would be better if you can add unit tests for the modified functions.
