### ISSUE TITLE
The LCAO SCF calculation is not stable

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#1945]
### Describe the bug

For below example 002_Li88Ge20, the SCF convergence process (ks_solver: genelpa) is different between the develop (20230223) and v3.1.0.
SCF of develop and V3.1.0:
![image](https://user-images.githubusercontent.com/91927439/220860041-e18b6ad3-8ff7-446d-9f5b-db18083a4cf8.png)

And for below example 008_Au1Mg63, the energies are -96871.37519226009 and -96871.37540433317 for develop and v3.1.0 respectively
SCF of develop and V3.1.0
![image](https://user-images.githubusercontent.com/91927439/220860909-a4d36905-e032-4ff6-a90d-e6c43f9eb96b.png)

[genelpa.zip](https://github.com/deepmodeling/abacus-develop/files/10812024/genelpa.zip)

**Comment by caic99** [comment]
@pxlxingliang `004_Li128C75H100O7` did not converge, plz see https://github.com/deepmodeling/abacus-develop/discussions/1948 . Maybe we should also take a look on that case.

**Comment by dyzheng** [comment]
I tested case 002_Li88Ge20, and the consequence is error caused by scalapack with intel-OneAPI compiler:
<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">
<head>

<meta name=Generator content="Microsoft Excel">

<style>

</style>
</head>
<body>



repeat | GNU | INTEL | v3.0.0 | v3.1.0 | v3.2.0
-- | -- | -- | -- | -- | --
1 | 20 | 28 | 100 | 22 | 25
2 | 20 | 100 | 22 | 20 | 27
3 | 20 | 57 | 21 | 26 | 29
4 | 20 | 24 | 22 | 24 | 31
5 | 20 | 33 | 28 | 29 | 21
6 | 20 | 28 | 28 | 20 | 37
7 | 20 | 27 | 21 | 38 | 23
8 | 20 | 29 | 23 | 28 | 28
9 | 20 | 97 | 54 | 29 | 26
10 | 20 | 89 | 28 | 31 | 37
11 | 20 | 23 | 26 | 24 | 100
AVERAGE | 20 | 48.63636364 | 33.90909091 | 26.45454545 | 34.90909091
STDEV | 0 | 31.4492376 | 23.82206769 | 5.33598419 | 22.17861378



</body>

</html>

**Comment by dyzheng** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">
<head>

<meta name=Generator content="Microsoft Excel">



</head>
<body>



  | v3.0.0-MPI | v3.0.0-OMP | v3.1.0-MPI | v3.1.0-OMP | v3.2.0-MPI | v3.2.0-OMP
-- | -- | -- | -- | -- | -- | --
1 | 0.000159746 | 0 | 1.851E-07 | 1.00408E-09 | 1.95898E-07 | 7.44985E-08
2 | 1.93599E-07 | 0 | 1.92202E-07 | 1.00408E-09 | -2.1077E-06 | 7.44985E-08
3 | 1.93961E-05 | 2.03727E-10 | 8.42701E-07 | 1.09867E-09 | 1.976E-07 | 7.46004E-08
4 | 2.24962E-05 | 2.03727E-10 | 1.933E-07 | 1.09867E-09 | 1.70403E-07 | 7.46004E-08
5 | -53.06598169 | 2.98314E-10 | 1.20906E-05 | 1.20053E-09 | 2.07401E-07 | 7.46004E-08
6 | 2.07598E-07 | 4.00178E-10 | 1.89604E-07 | 1.20053E-09 | -5.47474E-05 | 7.46004E-08
7 | 1.94203E-07 | 4.00178E-10 | 1.98299E-07 | 1.20053E-09 | -5.51987E-05 | 7.46004E-08
8 | 1.93599E-07 | 5.02041E-10 | 2.45702E-07 | 1.20053E-09 | -9.72022E-05 | 7.47023E-08
9 | 9.99804E-07 | 5.02041E-10 | -2.50563E-05 | 1.20053E-09 | 9.28723E-05 | 7.48041E-08
10 | -5.94137E-05 | 9.02219E-10 | 1.94501E-07 | 1.70257E-09 | 2.31303E-07 | 7.52043E-08



</body>

</html>

I have tested both OMP and MPI parallel calculation with Intel-OneAPI, "ETOT" results of MPI are unstable, while results of OMP has only little difference.

**Comment by dyzheng** [comment]
The "ETOT_" results between Intel-OneAPI and GNU with MPI parallel are:
<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">
<head>

<meta name=Generator content="Microsoft Excel">


</head>
<body>



  | Intel-MPI | GNU-MPI
-- | -- | --
1 | 8.49832E-09 | 0
2 | 0.024021312 | 2.98314E-10
3 | 1.1293E-05 | 2.98314E-10
4 | 0.000118751 | -1.01863E-10
5 | -2.13568E-05 | 1.01863E-10
6 | 2.2992E-09 | 2.98314E-10
7 | 0.00010504 | 6.03904E-10
8 | -0.000498763 | 2.03727E-10
9 | -9.26499E-07 | -1.96451E-10
10 | -0.000153989 | 1.01863E-10
11 | 5.02041E-10 | -1.96451E-10



</body>

</html>

In this table, we can find error of GNU-MPI is almost 1E-10 eV, which is same as  Intel-OMP(in table above)

**Comment by dyzheng** [comment]
With tools in #2328, I found the difference of single process and multi processes derived from Operator Veff.
The bug has not been solved now.

**Comment by dyzheng** [comment]
It has not been solved.

**Comment by dyzheng** [comment]
I find that small difference derived from this line:
https://github.com/deepmodeling/abacus-develop/blob/develop/source/module_elecstate/module_charge/charge.cpp#L634 
```
rho_basis->recip2real( &rho_g3d(is,0), rho_in[is]);
```
"rho_g3d" between mpi-1process and mpi-16process is same, but "rho_in" between mpi-1process and mpi-16process have small difference ( 2.51947168082(7760) vs 2.51947168082(9504) ), which lead to difference in Potential::Veff, Hamiltonian::HR_veff and Hamiltonian::HK_veff .

**Comment by dyzheng** [comment]
During my test, another bug occurred also in the line https://github.com/deepmodeling/abacus-develop/blob/develop/source/module_elecstate/module_charge/charge.cpp#L634 
normal rho_g3d will cause extremely large rho_in (~1e30), which lead to extremely high total number of electron , and rho will be set to zero in line https://github.com/deepmodeling/abacus-develop/blob/develop/source/module_elecstate/module_charge/charge.cpp#L690 .
I don't know how to repeat the bug environment, I just used v3.2.0 container and update OneAPI to newest version, but in same method I can't repeat this bug in another machine.

**Comment by dyzheng** [comment]
> I find that small difference derived from this line: https://github.com/deepmodeling/abacus-develop/blob/develop/source/module_elecstate/module_charge/charge.cpp#L634
> 
> ```
> rho_basis->recip2real( &rho_g3d(is,0), rho_in[is]);
> ```
> 
> "rho_g3d" between mpi-1process and mpi-16process is same, but "rho_in" between mpi-1process and mpi-16process have small difference ( 2.51947168082(7760) vs 2.51947168082(9504) ), which lead to difference in Potential::Veff, Hamiltonian::HR_veff and Hamiltonian::HK_veff .

I have found parts of "rho_g3d" in results of MPI-16-process is different from results of MPI-1-process:
```
> (9.42040221439137e-07,-2.18346762735125e-08)
< (9.42040222410413e-07,-2.18346754751178e-08)
```

**Comment by dyzheng** [comment]
> 

The error comes from line https://github.com/deepmodeling/abacus-develop/blob/develop/source/module_elecstate/module_charge/charge.cpp#L486  .
array "rho_lgl[ rho_basis->ig2igg[ig] ]" caused error.

**Comment by dyzheng** [comment]
I think the small errors are introduced by "rho_basis->gg_uniq[igg]" in line https://github.com/deepmodeling/abacus-develop/blob/develop/source/module_elecstate/module_charge/charge.cpp#L442 .
this array calculated in module_pw, @Qianruipku can you help for this problem?

**Comment by Qianruipku** [comment]
gg_uniq[igg] can be different in MPI-1 and MPI-16. Since if the module of G, that is gg_uniq are considered the same when they have a difference less than 1e-8. See  [ if (std::abs(tmpgg[ig] - tmpgg2[igg]) > 1.0e-8)](https://github.com/deepmodeling/abacus-develop/blob/2941456ef36a72ae575c167159f8d8baeb408803/source/module_basis/module_pw/pw_basis.cpp#L182)

You can reduce 1e-8 to 1e-10. However, that will increase the length of array gg_uniq.

**Comment by wenfei-li** [comment]
I am confused. The G vectors are discrete, how come there are numerical discrepancies?
From what I understand the size of G will not be that large, so why not generate them on rank 0 and distribute them to other ranks?

**Comment by hongriTianqi** [comment]
- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by pxlxingliang** [comment]
I tested this case on Bohrium by using c32_m64_cpu machine, and the repeated 10 runs (command is: OMP_NUM_THREADS=1 mpirun -np 16 abacus) have different results:
![1d0831b2285b0ac7cdff95c402030a24__fallback_source=1 height=1280 mount_node_token=AaqWdcpyIowNx9xngm7cGn7enAc mount_point=docx_image policy=equal width=1280](https://github.com/deepmodeling/abacus-develop/assets/91927439/0ff2a690-678f-4311-8bed-11598d11b621)
and the drho is:
![1ab9c7107a3b8f840570c80a26838164__fallback_source=1 height=1280 mount_node_token=CXxsdiJDIoqJedxAgsRcR5qGnad mount_point=docx_image policy=equal width=1280](https://github.com/deepmodeling/abacus-develop/assets/91927439/224ccc64-4a87-440b-bdd2-a86d7bae78aa)


While if I reduce the mpi parallel cores to 4, all 5 repeated runs have the same results (all the SCF steps are 20 and the energy are same). 

When I use c32_m128_cpu machine to run the test, the results are stable, and all 10 repeated SCF runs are converged by 20 steps. 

Although we have not found the cause of instability on the c32_m64_cpu machine, it can indeed run stably on the c32_m128_cpu machine. And we have switched to use c32_m128_cpu in the latter daily test.
