### ISSUE TITLE
energy cutoff for LCAO

### ISSUE THREAD

**Issue by jinzx10** [deepmodeling/abacus-develop#1996]
### Details

Currently the k mesh for LCAO radial Fourier transform (1D integration) is determined by ecutwfc and dk, where ecutwfc comes from INPUT having a typical value ~100, and dk by default is 0.01. For the nonlocal projector beta(r), I checked whether two successive transforms (carried out by Numerical_Nonlocal_Lm::get_kradial()) brings back the original beta(r), and plot the error below. The UPF file used for testing is PP_ORB/O_ONCV_PBE-1.0.upf, and all 4 beta projectors are tested.

The error shows that typical ecutwfc values, which is drawn from the 3D Fourier transform of charge density & wavefunction, might be inadequate for the radial Fourier transform. The convergence with respect to dk is yet to be studied.

![err_beta_r2k2r_ecut](https://user-images.githubusercontent.com/26805483/222624255-d61668c5-48f3-4238-9769-650c9931795a.png)

**Comment by dyzheng** [comment]
What will you do with this issue?

**Comment by mohanchen** [comment]
I will discuss this with zx

**Comment by hongriTianqi** [comment]
- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by jinzx10** [comment]
By switchiing to an FFT-based spherical Bessel transform method, this problem is systematically solved by https://github.com/deepmodeling/abacus-develop/pull/2904.
