### ISSUE TITLE
Different energy level when doing scf calculation with LCAO or PW basis

### ISSUE THREAD

**Issue by ESROAMER** [deepmodeling/abacus-develop#2001]
### Details

I was testing my newly generated LCAO basis set. I got energy levels of CH4 molecular with my basis using scf calculation and compared the result with PW basis. The energy level of the occupied states was well matched. But in the case of unoccupied states, it was totally different. (Left:LCAO right:PW)  
<img width="583" alt="4" src="https://user-images.githubusercontent.com/104255052/222742752-662b38a8-599c-4fff-98d2-a68276fb7475.png">
I thought maybe there is something wrong with my basis, so I done the same test to the basis provided on the website of ABACUS. But the result didn't change much.
Is that a problem of ABACUS or DFT theory itself, or a problem of my input paras? I also packed my input file for you to check. I'd appreciate it if you can give me a answer or a solution to this, thanks!
[scf.zip](https://github.com/deepmodeling/abacus-develop/files/10882802/scf.zip)
[input_SG15_PBE.zip](https://github.com/deepmodeling/abacus-develop/files/10883310/input_SG15_PBE.zip)

**Comment by dyzheng** [comment]
Maybe you can try suggestions below:
1. increase ecutwfc from 60 to 100 Ry.
2. test unitcell with multi k-points for both PW and LCAO basis, compare results with single molecules.

**Comment by ESROAMER** [comment]
> Maybe you can try suggestions below:
> 
> 1. increase ecutwfc from 60 to 100 Ry.
> 2. test unitcell with multi k-points for both PW and LCAO basis, compare results with single molecules.

Thanks for your suggestions! I'm not quite sure if I've done the test exactly what you want me to do, but the result doesn't change much. I have even tried to increase the ecutwfc to 400Ry. I packed up my output files in the case of multi-k, you may check them as well.
[SCF_multi_K.zip](https://github.com/deepmodeling/abacus-develop/files/10893869/SCF_multi_K.zip)

**Comment by kirk0830** [comment]
In my opinion it is common to see high-lying energy levels are not precisely predicted by AO basis. I used to discover something similar when comparing band structures calculated by QE (PW basis) and CP2K (GTO+PW). If you really need to have a precise prediction of unoccupied bands, for PW basis, you need to increase cutoff value and for NAO, basis with higher angular momentum is usually needed. For this problem is somewhat general and I indeed ask @mohanchen some similar questions, . Even in quantum chemistry, there is a term called Rydberg excitation, which describes a special kind of excitation where excited electrons are significantly delocalized. To have a not-bad description, AO should contain more smearing functions (e.g., from ground state-enough the cc-pVTZ to aug-cc-pVTZ basis set).
Due to majority of properties only depend on ground state electronic structure, in most time you do not need to worry too much ;)

**Comment by ESROAMER** [comment]
> In my opinion it is common to see high-lying energy levels are not precisely predicted by AO basis. I used to discover something similar when comparing band structures calculated by QE (PW basis) and CP2K (GTO+PW). If you really need to have a precise prediction of unoccupied bands, for PW basis, you need to increase cutoff value and for NAO, basis with higher angular momentum is usually needed. For this problem is somewhat general and I indeed ask @mohanchen some similar questions, . Even in quantum chemistry, there is a term called Rydberg excitation, which describes a special kind of excitation where excited electrons are significantly delocalized. To have a not-bad description, AO should contain more smearing functions (e.g., from ground state-enough the cc-pVTZ to aug-cc-pVTZ basis set). Due to majority of properties only depend on ground state electronic structure, in most time you do not need to worry too much ;)

Thank you very much for your detailed response! Similiar problem indeed exists on other softwares. It seems to be a commom problem of NAOs itself rather than a flaw of ABACUS. I'm quite interested in what specific infulence this flaw will have on the simulation, but I suppose that's somthing only needed to be considered only when the specific problem arises in the future.
