### ISSUE TITLE
Structure limit by int variable

### ISSUE THREAD

**Issue by dyzheng** [deepmodeling/abacus-develop#2002]
### Describe the bug

In this case:
[C_12_k1_1-56_pbe_g.zip](https://github.com/deepmodeling/abacus-develop/files/10887909/C_12_k1_1-56_pbe_g.zip)

Using command "OMP_NUM_THREADS=16 mpirun -np 1 abacus ":
Error occured:
```
===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 0 PID 10664 RUNNING AT iZ8vb1kd70dv457fqaw4boZ
=   KILLED BY SIGNAL: 11 (Segmentation fault)
===================================================================================
```
and in running_scf.txt:
```
vlocal exchange index is built
                          buffer size(M): = 9075
                    buffer index size(M): = 17592186037107
 vlocal data are put in sender_buffer, size(M): = 441
 vlocal data are exchanged, received size(M): = 441
```
It caused by: 
https://github.com/deepmodeling/abacus-develop/blob/develop/source/module_gint/gint_gamma.h#L59
limits size(INT_MAX) of memory to 8GB, but this case should be 9GB.

It maybe related to MPI_Count limits.

**Comment by caic99** [comment]
@dyzheng Maybe using `size_t` is more adequate here? I'll see if it is recommended/required by MPI standard.

**Comment by caic99** [comment]
MPI only allows int as the content length, but not size_t. Maybe we have to split them into multiple operations. @dyzheng

**Comment by PeizeLin** [comment]
> MPI only allows int as the content length, but not size_t. Maybe we have to split them into multiple operations. @dyzheng

New functions `MPI_xxx_c()` using `MPI_Count` instead of `int` are contained in MPI-4.0.
We can update the codes in ABACUS to
```C++
#if MPI_VERSION>=4
    MPI_Send_c(...);
#else
    MPI_Send(...);
#endif
```

**Comment by hongriTianqi** [comment]
- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by dyzheng** [comment]
The latest version(3.4.0) is okay for this case.
Thanks for testing from @LiuXiaohui123321 .
