### ISSUE TITLE
ABACUS is slower than QE by using dav

### ISSUE THREAD

**Issue by iduygnay** [deepmodeling/abacus-develop#2128]
### Describe the bug

Please find attached the files of the input and the output from ABACUS and QE respectively. The runtime of abacus is almost 10 times of qe. the input and the Pseudopotentials are the same, ecut are the same, kpoints are the same, and the structures are the same. 
[test.zip](https://github.com/deepmodeling/abacus-develop/files/11047148/test.zip)

### Expected behavior

Maybe the run time of the two software should be almost same

### To Reproduce

run abacus and run qe

### Environment

I used qe7.0 but any version should be fine.

**Comment by dyzheng** [comment]
@mohanchen Do you know anyone can help for this issue?

**Comment by mohanchen** [comment]
Haozhi and Denghui.

**Comment by hongriTianqi** [comment]
- [ ] Reproduce the performance issue on a similar system or environment.
- [ ] Identify the specific section of the code causing the performance issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified performance issue.
- [ ] Implement the chosen solution to address the performance issue.
- [ ] Test the implemented solution to ensure it improves performance without introducing new issues.
- [ ] Optimize the solution if necessary, considering trade-offs between performance and other factors (e.g., code complexity, readability, maintainability).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Merge the improved solution into the main codebase and notify the issue reporter.

**Comment by haozhihan** [comment]
I find the parameter of the coordinate system in the test file of this case was incorrect. 
Actually, there is not such a big gap. So I close this issue.
