### ISSUE TITLE
SOC test set request

### ISSUE THREAD

**Issue by Shen-Zhen-Xiong** [deepmodeling/abacus-develop#2535]
### Details

Can we provide a set of SOC tests

**Comment by hongriTianqi** [comment]
- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by hongriTianqi** [comment]
- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by Shen-Zhen-Xiong** [comment]
[case_FeCl2.tar.gz](https://github.com/deepmodeling/abacus-develop/files/13838641/case_FeCl2.tar.gz)
[case_BiSe.tar.gz](https://github.com/deepmodeling/abacus-develop/files/13838642/case_BiSe.tar.gz)
[case_C.tar.gz](https://github.com/deepmodeling/abacus-develop/files/13838643/case_C.tar.gz)
[case_CBN.tar.gz](https://github.com/deepmodeling/abacus-develop/files/13838644/case_CBN.tar.gz)
[case_CoSnS.tar.gz](https://github.com/deepmodeling/abacus-develop/files/13838645/case_CoSnS.tar.gz)
[case_MnSbTe.tar.gz](https://github.com/deepmodeling/abacus-develop/files/13838646/case_MnSbTe.tar.gz)
[case_CsPbI3.tar.gz](https://github.com/deepmodeling/abacus-develop/files/13838647/case_CsPbI3.tar.gz)
There are some cases can be used for test SOC

**Comment by hongriTianqi** [comment]
This is not a good practice as it does not assist improving the code itself.

**Comment by mohanchen** [comment]
We will close this issue since no more progress will be expected based on this issue. We always welcome new issues.
