### ISSUE TITLE
esolver_of.cpp needs to be simplified

### ISSUE THREAD

**Issue by mohanchen** [deepmodeling/abacus-develop#2544]
### Describe Current Status and Possible Solution

Now the esolver_of.cpp in source/module_esolver takes over a thousand lines. The detailed algorithms can be moved to the /module_hamilt_pw/hamilt_ofdft directory.

**Comment by hongriTianqi** [comment]
- [ ] Identify the specific code file or section with the code quality issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified issue.
- [ ] Refactor the code to improve code quality, following the suggested solution.
- [ ] Ensure the refactored code adheres to the project's coding standards.
- [ ] Test the refactored code to ensure it functions as expected.
- [ ] Update any relevant documentation, if necessary.
- [ ] Submit a pull request with the refactored code and a description of the changes made.
