### ISSUE TITLE
The GPU code needs to be reorganized

### ISSUE THREAD

**Issue by mohanchen** [deepmodeling/abacus-develop#2546]
### Describe Current Status and Possible Solution

Currently, the GPU code scatters around the package, we need to reorganize the codes.

**Comment by hongriTianqi** [comment]
- [ ] Identify the specific code file or section with the code quality issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified issue.
- [ ] Refactor the code to improve code quality, following the suggested solution.
- [ ] Ensure the refactored code adheres to the project's coding standards.
- [ ] Test the refactored code to ensure it functions as expected.
- [ ] Update any relevant documentation, if necessary.
- [ ] Submit a pull request with the refactored code and a description of the changes made.

**Comment by denghuilu** [comment]
[ABACUS 代码存放规范](https://mcresearch.gitee.io/abacus-user-guide/develop-rule.html)
