### ISSUE TITLE
The more ncpus, but the time of one step in scf almost no change

### ISSUE THREAD

**Issue by scott-5** [deepmodeling/abacus-develop#2563]
### Describe the bug

The same input file takes almost the same amount of time to calculate using different cpu cores on the same node. Here are the specific situations:
1. The complete test node is occupied separately by myself.
2. The test is divided into three groups. The first is run by `mpirun -n 1` with increasing threads. The second is run by `mpi -n 2` with increasing threads. The last is run by `OMP_NUM_THREADS=8` with increasing processes. The test results show that, except for the case where there is very little ncpus, the time of single scf steps remains almost unchanged as the number of CPUs increases.

### To Reproduce

Here is the file used to reproduce the test.
[test.zip](https://github.com/deepmodeling/abacus-develop/files/11595125/test.zip)

### Environment

OS: CentOS 7
ABACUS version: 3.2.3 (installed by Conda)

**Comment by Satinelamp** [comment]
I also meet the same problem in practice, there should be a test of speedup of abacus when using multiple cores. I belive that Prof. He lixin and collorators are working on a  benchmark case.

**Comment by scott-5** [comment]
I hope that developers can incidentally test the computational efficiency of pw, I roughly compared the scf calculations of VASP and ABACUS_pw for the same k points(within Brillouin) at the same node:
```
INPUT_PARAMETERS
symmetry                1
ecutwfc                 50
basis_type              pw
scf_thr                 1e-4
scf_nmax                100
ksolver                 dav
smearing_method gauss
smearing_sigma  0.008
```
```
GGA    = PE
LREAL  = Auto
ALGO   = Normal
ENCUT  = 400
LWAVE  = .FALSE.
LCHARG = .FALSE.
ISIF   =  2
ISMEAR = 0
SIGMA  = 0.1
EDIFF  = 1E-4
IBRION = -1
```
I found single-step scf to be about an order of magnitude slower than VASP, although abacus takes only fewer electronic steps. It is also about four times slower in terms of final completion time. In fact a difference of 50% or less is tolerable for me. But I am not sure if the difference is mainly due to my input and environment or the code itself.

**Comment by hongriTianqi** [comment]
- [ ] Reproduce the performance issue on a similar system or environment.
- [ ] Identify the specific section of the code causing the performance issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified performance issue.
- [ ] Implement the chosen solution to address the performance issue.
- [ ] Test the implemented solution to ensure it improves performance without introducing new issues.
- [ ] Optimize the solution if necessary, considering trade-offs between performance and other factors (e.g., code complexity, readability, maintainability).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Merge the improved solution into the main codebase and notify the issue reporter.

**Comment by dyzheng** [comment]
@scott-5 Efficiency of LCAO basis for MPI parallelation has been improved in version v3.4.0. 
Can you test the case again and check if the problem is still existed?

**Comment by scott-5** [comment]
With the increase of ncpu, there is a significant acceleration of scf.
