### ISSUE TITLE
Surface relax calculation CANNOT be speeded up by change xy-periodic to yz-periodic

### ISSUE THREAD

**Issue by QuantumMisaka** [deepmodeling/abacus-develop#2586]
### Describe the bug

I noticed that ABACUS chose to parallelize the grid points along the z direction, it is recommended to construct model by xy- or yz-periodic direction. But in surface chemistry, lots of model were constructed by xy-periodic direction, so I tried my system in traditional xy-periodic and yz-periodic direction

[Fe5C2-CHCOH_xy2yz.tar.gz](https://github.com/deepmodeling/abacus-develop/files/11630965/Fe5C2-CHCOH_xy2yz.tar.gz)
 
In my test, I notice that it is surely quicker in SCF-calculation, but when I want to get a relaxed structure and energy, yz-periodic direction need more relaxation step, which lead to more calculation costs.

Is there anyone have an explanation?

### Expected behavior

yz- or xz- direction 2D-surface calculation should be speeded up NOT ONLY by SCF-calculation

### To Reproduce

- Model Construction: 
- - xy model: in paper
- - yz model: use "400: redefine lattice" in ATOMKIT 0.3.1 to transform from xy model
- - OMP_NUM_THREADS=4, 64core calculation (16core calculation also done, but will FAIL in yz-model, which is another problem)
- - Other setting in abacus.slurm and INPUT, KPT, STRU

### Environment

- ABACUS version: 3.2.3
- Platform: Intel Platinum 8358, Rockylinux8
- Compile method: by GNU toolchain from gcc-12.2.0 (specifically in https://blog.csdn.net/weixin_44471577/article/details/130815345 )

### Additional Context

The parallel computing method by LCAO basis set should by optimized, in the system above, VASP can have 4-times speed-up in 64core contrast by 16core, but ABACUS by LCAO can only speed up for 2 times.

**Comment by hongriTianqi** [comment]
- [ ] Reproduce the performance issue on a similar system or environment.
- [ ] Identify the specific section of the code causing the performance issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified performance issue.
- [ ] Implement the chosen solution to address the performance issue.
- [ ] Test the implemented solution to ensure it improves performance without introducing new issues.
- [ ] Optimize the solution if necessary, considering trade-offs between performance and other factors (e.g., code complexity, readability, maintainability).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Merge the improved solution into the main codebase and notify the issue reporter.

**Comment by QuantumMisaka** [comment]
It seems problem lies in the redefine lattice method of Materials Studio.
If use `405, switch axis` method in `ATOMKIT` to switch y-axis and z-axis, the calculation performance will have huge enhancement when do surface calculation
especially in v3.4.0 ABACUS
