### ISSUE TITLE
Out of Memory for AIMD Calculation

### ISSUE THREAD

**Issue by iduygnay** [deepmodeling/abacus-develop#2635]
### Describe the bug

I ran an AIMD case that loaded the DPKS model when it ran to more than 160 ionic steps, it reported that 'out of memory'. 
I remember that this bug was repaired so I don't know whether the different version causes this. 
Please find attached the files of my case.
[ACBN0-AIMD.zip](https://github.com/deepmodeling/abacus-develop/files/11743129/ACBN0-AIMD.zip)

### Expected behavior

I hope that it can report out of memory at the beginning. That really helped me to save my time.

**Comment by ouqi0711** [comment]
The first thing we need to check is whether this issue is introduced by DeePKS (which is not likely). To do so, we suggest that you turn off the deepks_scf flag and run a pure PBE AIMD job. If the same error is reported, we'll take a close look at the MD part; otherwise the DeePKS part will be checked.

**Comment by iduygnay** [comment]
Up to now, the AIMD without the DPKS model is running for more than 4 days, around 1400 ionic steps, and there's no oom report. So I think that might be caused by the DPKS.

**Comment by iduygnay** [comment]
I increased the memory for the node, then it calculated for 6 days and reported out of memory.

**Comment by hongriTianqi** [comment]
- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by WHUweiqingzhou** [comment]
@iduygnay,
we fix a memory leak bug recently, could you double-check if the problem has been solved for ABACUS  v.3.5.2?

**Comment by iduygnay** [comment]
This issue now is solved.
