### ISSUE TITLE
any tutorials to debug abacus?

### ISSUE THREAD

**Issue by Satinelamp** [deepmodeling/abacus-develop#2665]
### Details

If I want to try to debug abacus, is there any tutorials?
For example, this issue https://github.com/deepmodeling/abacus-develop/issues/2656 shows an error of  `Floating point exception`,  how could I find the code that trigger this error?

**Comment by caic99** [comment]
Hi @Satinelamp ,
Please refer to the manual: https://abacus.deepmodeling.com/en/latest/CONTRIBUTING.html#debugging-the-codes

**Comment by Satinelamp** [comment]
Thanks. @caic99 
I got two more questions about the relationship between `gcc` and `intel oneAPI` :
1. since intel oneAPI already has the `intel c++ compiler`, do I still need to use `gcc` as the dependency of `ABACUS`? 
2. I use `inte oneAPI` to compile `ABACUS`, why could I use `gdb` to debug `ABACUS`, I thought that `gdb` is only a part of `gcc`?

**Comment by caic99** [comment]
> Thanks. @caic99 I got two more questions about the relationship between `gcc` and `intel oneAPI` :

> 1. since intel oneAPI already has the `intel c++ compiler`, do I still need to use `gcc` as the dependency of `ABACUS`?

Intel classical c/c++ compiler `icc`, it uses GCC headers, linker, and libraries - more precisely, GNU tools. That means, GCC components should be present on the system, while not being directly used. For `icx`, the situation is similar, but I have not tested the case without GCC. 
Please see: 
- https://abacus.deepmodeling.com/en/latest/quick_start/easy_install.html#prerequisites
- https://www.intel.com/content/www/us/en/docs/cpp-compiler/developer-guide-reference/2021-8/gcc-compatibility-and-interoperability.html
- https://www.intel.com/content/www/us/en/docs/dpcpp-cpp-compiler/developer-guide-reference/2023-1/gcc-compatibility-and-interoperability.html

> 2. I use `inte oneAPI` to compile `ABACUS`, why could I use `gdb` to debug `ABACUS`

The format for executable files on the Linux platform is called ELF (Executable and Linkable Format). It is recognizable for the operating system and the debugger, regardless of the compiler used to generate that executable.

>  I thought that `gdb` is only a part of `gcc`?

That's right. Intel used to have its own debugger `idb`, but deprecated since long ago. `gdb` is sufficient for most cases. For LLVM toolchain, there exists `lldb`.
