### ISSUE TITLE
Too slow to compile ABACUS with UNIT tests

### ISSUE THREAD

**Issue by Qianruipku** [deepmodeling/abacus-develop#2732]
### Describe Current Status and Possible Solution

![image](https://github.com/deepmodeling/abacus-develop/assets/76200646/1ccc79be-f0cb-4dd7-8210-4032791c15d0)
It costs 42 min to run "build with gnu compiler...."
And some cpp files like atom_spec.cpp are compiled for 24 times!

**Comment by caic99** [comment]
Hi @Qianruipku ,
This dilemma comes from the coupling between codes, affecting the compilation of UTs. Please see #670 for an example of how this happenes and how to fix it. 
To accelerate the compilation tests, we can skip building UTs in the building test, since the correctness of building UTs is ensured in another action of running UTs. What do you think? @baixiaokuang 
cc @mohanchen @dyzheng
