### ISSUE TITLE
to use the same default value of 'scf_thr' parameter for different basis

### ISSUE THREAD

**Issue by LiuXiaohui123321** [deepmodeling/abacus-develop#2846]
### Describe Current Status and Possible Solution

I am testing the stability and convergence efficiency of ABACUS with default parameter settings, and I found that the 'scf_thr' parameter has different default values for PW and LCAO basis (https://abacus.deepmodeling.com/en/latest/advanced/input_files/input-main.html#scf-thr). Why do we use different default values for two basis, and is it considered to use the same default value, for example 1.0e-7?

**Comment by hongriTianqi** [comment]
- [ ] Identify the specific code file or section with the code quality issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified issue.
- [ ] Refactor the code to improve code quality, following the suggested solution.
- [ ] Ensure the refactored code adheres to the project's coding standards.
- [ ] Test the refactored code to ensure it functions as expected.
- [ ] Update any relevant documentation, if necessary.
- [ ] Submit a pull request with the refactored code and a description of the changes made.

**Comment by sunliang98** [comment]
Under different type of basis, the formula of convergence criterion $\Delta\rho$ for SCF calculation is different, so that the default `scf_thr` should be different. One can set the definition of $\Delta\rho$ with parameter [`scf_thr_type`](https://abacus.deepmodeling.com/en/latest/advanced/input_files/input-main.html#scf-thr-type).

**Comment by LiuXiaohui123321** [comment]
> Under different type of basis, the formula of convergence criterion Δρ for SCF calculation is different, so that the default `scf_thr` should be different. One can set the definition of Δρ with parameter [`scf_thr_type`](https://abacus.deepmodeling.com/en/latest/advanced/input_files/input-main.html#scf-thr-type).

Thanks for your reply!
In fact, the problem here is initially related to the SCF convergence efficiency of the ABACUS PW basis set. We compared the convergence efficiency of ABACUS and other DFT software through some test examples, and found that the steps of ABACUS is generally high. If we adjust the value of `scf_thr`, e.g., 1.0e-6, the steps will be reduced, and it seems to have little effect on the total energy after convergence. 
![图片1](https://github.com/user-attachments/assets/38139eff-811a-4413-8390-1928eeee8f68)
![图片2](https://github.com/user-attachments/assets/0f348321-264f-4b45-8460-0877cacf432b)
So, do we consider appropriately lowering the default value of `scf_thr` under the PW basis set.

**Comment by WHUweiqingzhou** [comment]
You can use the same `scf_ene_thr`, while cannot use the same `scf_thr` due to different definition.
