### ISSUE TITLE
to set reasonable default values for 'smearing_method' and 'smearing_sigma' parameters

### ISSUE THREAD

**Issue by LiuXiaohui123321** [deepmodeling/abacus-develop#2847]
### Describe Current Status and Possible Solution

I am testing the stability and convergence efficiency of ABACUS with default parameter settings, and I found that for some test cases, especially those with a small gap or those that are metallic, they do not converge when using the default values of 'smearing_method' and 'smearing_sigma'.

- about 'smearing_method': https://abacus.deepmodeling.com/en/latest/advanced/input_files/input-main.html#smearing-method
- about 'smearing_sigma': https://abacus.deepmodeling.com/en/latest/advanced/input_files/input-main.html#smearing-sigma

Here are some test results when using the default values, and we can see that close to half of the test cases fail to converge,
https://hsemf3oqjj.feishu.cn/docx/TwygdUI2Wo8AjRxpobccQ3O3nZf#SXdHdB4BWoDQq6xCIoNc0svunUC

If we adjust 'smearing_method' to **gauss** and set 'smearing_sigma' to **0.2eV** (the default value used by vasp, https://www.vasp.at/wiki/index.php/SIGMA) or **0.02Ry**, almost all the test cases can converge,
https://hsemf3oqjj.feishu.cn/docx/TwygdUI2Wo8AjRxpobccQ3O3nZf#HI7bdWMceoHPWOxSL1TcIPYPnGh

**Comment by hongriTianqi** [comment]
- [ ] Identify the specific code file or section with the code quality issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified issue.
- [ ] Refactor the code to improve code quality, following the suggested solution.
- [ ] Ensure the refactored code adheres to the project's coding standards.
- [ ] Test the refactored code to ensure it functions as expected.
- [ ] Update any relevant documentation, if necessary.
- [ ] Submit a pull request with the refactored code and a description of the changes made.

**Comment by WHUweiqingzhou** [comment]
This issue is closed after PR #3337.
