### ISSUE TITLE
symmetry bug

### ISSUE THREAD

**Issue by AroundPeking** [deepmodeling/abacus-develop#2853]
### Describe the bug

System: single silicon atom

Bug: Changing `symmetry` from 1 to -1, pbe energy changes a lot. See below `dia_Si_1.out` and `dia_Si_-1.out` respectively.

illustration: `smearing_sigma` is set to 1e-20 to prevent from fractional occupation.

### To Reproduce

abacus: v3.3.2
Commit: e39b50e (Fri Aug 18 16:14:25 2023 +0800)
[single.zip](https://github.com/deepmodeling/abacus-develop/files/12407961/single.zip)

**Comment by maki49** [comment]
This is an `nspin=2` case. It does not converge with `symmetry=0` too. 
I guess it might be related to the breaking of time-reversal symmetry (but I'm not sure). 
I will test this case with VASP and investigate the related theory deeper.  
(But currently my workstation cannot run VASP due to a strange segment fault. So if anyone can help to test this case with VASP, it will save me much time, thanks. )

**Comment by minyez** [comment]
@maki49 segment fault for single atom calculation (typically large supercell) in VASP might be related to limited stacksize. `ulimit -s unlimited` might help in your case.

**Comment by dyzheng** [comment]
One solution is to compare the reduced k-points between ABACUS and VASP, you can set extremely low ENCUT with VASP to avoid the limited stacksize. If time-reversal symmetry is broken, symmetry can only be set to -1 in current version of ABACUS.

**Comment by maki49** [comment]
@minyez  Thanks for pointing out the cause. Using more cores can also work. 
@dyzheng only gamma point is used in this case, so it has nothing to do with reducing k-points. The only thing matters is charge density symmetrization. Real- and recip-space symmetrization gives the same energy (-1.021128e+02 eV) when `symmetry=1`.


If the initial magnetic moment is set to 2 (absolute value with 4 valence electrons, rather than 0.5 in the provided STRU file), `symmetry=1` gives  the same energy (-1.021128e+02 eV), while `symmetry=-1` cannot converge. Here're the logs:
[symm-1_mag2.log](https://github.com/deepmodeling/abacus-develop/files/12430486/symm-1_mag2.log)
[symm1_mag2.log](https://github.com/deepmodeling/abacus-develop/files/12430487/symm1_mag2.log)
The same phenomenon (symmetry-on, converge; symmetry-off, not converge) also happens in VASP (ENCUT=100 eV for a quick test, SIGMA=1.01e-5)
[vasp-1Si-spin2.zip](https://github.com/deepmodeling/abacus-develop/files/12430600/vasp-1Si-spin2.zip)


VASP refuses too-small smearing sigma less than 1e-5, which reminds me of testing a larger smearing_sigma. `symmetry=1` and `symmetry=-1` in ABACUS give the same energy (-1.025258e+02 eV) when `smearing_sigma=1e-2`.

In a word, it seems more like an error sensitivity (with too-small smearing_sigma and initial magmom) rather than a symmetry bug.

**Comment by AroundPeking** [comment]
@maki49 Thanks for your test. Would you check the occupation when `smearing_sigma=1e-2` and `magnetic moment=2`?  A larger `smearing_sigma` I used before always led to fractional occupation, except for `1e-20`.

**Comment by maki49** [comment]
@AroundPeking Yes, the fracitonal occupation is consistent with VASP:
```
SPIN UP : 
 1/1 kpoint (Cartesian) = 0.0000 0.0000 0.0000 (0 pws)
       1       -11.0731        1.00000
       2       -4.24871       0.666667
       3       -4.24871       0.666667
       4       -4.24871       0.666667
       5        8.87557        0.00000
SPIN DOWN : 
 1/1 kpoint (Cartesian) = 0.0000 0.0000 0.0000 (0 pws)
       1       -9.28818        1.00000
       2       -2.54356        0.00000
```
Is there anything wrong with fractional occupation in ABACUS(PBE) ?

**Comment by AroundPeking** [comment]
Actually, after the PBE calculation, RPA@PBE calculation will be conducted, in which fractional occupation leads to bad RPA correlation energy.

**Comment by maki49** [comment]
> Actually, after the PBE calculation, RPA@PBE calculation will be conducted, in which fractional occupation leads to bad RPA correlation energy.

@AroundPeking Got it. 
For current use, `symmetry=1` is recommended because it's stable when `smearing_sigma` is extremely small, while `symmemtry=0 or -1` is sensitive to initial magmom and suffers from another problem: https://github.com/deepmodeling/abacus-develop/issues/2864.
(Looking forward to the solution to RPA problem https://github.com/deepmodeling/abacus-develop/issues/2600.)

**Comment by AroundPeking** [comment]
@maki49 OK, thanks for your help.

**Comment by hongriTianqi** [comment]
@AroundPeking Could you please give a summary of this issue, for example, what was learned from this issue and what is suggested for improving the performance of ABACUS later? Thank you.
