### ISSUE TITLE
Understanding the structure of member variable T* psi::Psi::psi and function psi::Psi::to_range()

### ISSUE THREAD

**Issue by kirk0830** [deepmodeling/abacus-develop#2880]
### Details

in namespace `psi`, there is a struct named `range` and, it has variables:
`k_first`: indicating whether kpoint is the first index of `psi::Psi::psi` array
`index_1`: the value of the first index of `psi::Psi::psi`
`range_1` and `range_2` are something like iterator's `begin()` and `end()`.
in class `psi::Psi`, there is a member function `to_range()`, in its body I find:
![image](https://github.com/deepmodeling/abacus-develop/assets/67682086/c0c5731a-88e5-4a41-a16d-232ed086ead9)
for not mem_saver case, the first logic branch is for inconsistency cases and illegal cases, but for the second branch, does it mean merely the `k_first = true` case is supported, while the counterpart, `k_first = false` is not really implemented?

**Comment by hongriTianqi** [comment]
- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by kirk0830** [comment]
Well it seems the band-first method for indicing psi element is not really implemented
