### ISSUE TITLE
The Wannier90 interface with lcao basis depends on mpi

### ISSUE THREAD

**Issue by hongriTianqi** [deepmodeling/abacus-develop#2899]
### Describe the bug

The Wannier90 interface with lcao basis depends on mpi processor numbers. Hidden bug exists on parallel when running lcao code to output MLWFs. The behavior is that amn and mmn are different when run nscf calculation with different number of processors.

### Expected behavior

amn and mmn results should not depends on number of processors.

### To Reproduce

1. go to abacus-develop/examples/interface_wannier90/ABACUS_towannier90_lcao
2. run scf calculation
3. run nscf calculation with different number of processors
4. check amn and mmn matrices

**Comment by hongriTianqi** [comment]
- [x] Verify the issue is not a duplicate.
- [x] Describe the bug.
- [x] Steps to reproduce.
- [x] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by jingan-181** [comment]
1. I used 2, 4, and 8 CPU cores to calculate the Wannier function. Although the `amn` and `mmn` files output by ABACUS have inconsistent results under different core numbers, the MLWF generated by Wannier90 is consistent (the same Wannier center, spread, and Wannier function real space distribution).
2. For the explanation of this phenomenon, I think it is this: when the energy band of a certain k point appears degenerate, under different core numbers, although the energy band $E_{nk}$ is consistent, $\Psi_{nk }$ are different (degenerate states will be mixed). This will cause the calculated `mmn` and `amn` to be inconsistent under different cores, because these files depend on $\Psi_{nk}$. Although the files will be different, the physical nature will not change.

**Comment by jingan-181** [comment]
3. One more thing, I guess. Under different CPU cores, the wave function calculated through diagonalization will have a random phase degree of freedom. This is also a reason for file inconsistency.

**Comment by hongriTianqi** [comment]
@jingan-181 Thanks for your response. My concern is how to add an integrated case test for this function. If the `amn` and `mmn` changing is normal, then we might find other ways to compare any other files to add an integrated case test.

**Comment by jingan-181** [comment]
This issue can be closed. If integration testing of the Wannier90 interface is needed, you can fix the matrix diagonalization solver of ABACUS and the number of CPU cores used, then compare the files.
