### ISSUE TITLE
Calculating kinetic energy density with LCAO

### ISSUE THREAD

**Issue by wenfei-li** [deepmodeling/abacus-develop#291]
**Is your feature request related to a problem? Please describe.**
In order to implement meta-GGA with LCAO, a subroutine for calculating kinetic energy density with LCAO is required.
The kinetic energy density is defined as:
![image](https://user-images.githubusercontent.com/38569667/129693571-e4a2685c-bad4-4361-b75a-dbed5a2760f7.png)
where f(i) is the occupation number of state i, and the index i runs over all bands and k points.

**Describe the solution you'd like**
It would be nice if there is a subroutine that converts density matrix to tau that is similar to cal_rho which converts density matrix to the electron density rho(r).

**Comment by mohanchen** [comment]
In order to obtain the kinetic energy density, 'grid integration' should be done. First, we need to expand \nable psi (here psi is the wave functions of the system) into atomic orbitals, and then we need to obtain the derivative of atomic orbitals with respect to r (which is already tabulated from read-in atomic orbitals), and then add some code lines in Gint_Tools::cal_psir_ylm in order to get derivative of psir with respect to r. Once the above operations have been done, one needs to evaluate the kinetic energy density once the charge density is updated in meta-GGA calcualtions.

**Comment by wenfei-li** [comment]
The functionality has been implemented, as well as mGGA in LCAO basis. #1135
