### ISSUE TITLE
ABACUS nscf spends much more time than QE/pw.x.

### ISSUE THREAD

**Issue by Liu-RX** [deepmodeling/abacus-develop#2914]
### Details

I'm calculating a system with 63 water molecules and an additional proton with SCF and NSCF. I want to generate the `eig`, `amn` and `mmn`files for the Wannier90 software to use. However, it turns out that ABACUS requires much longer time to get the job done. It takes the QE several minutes to do the calculation, but takes ABACUS several hours to do so.
The used functional is SCAN, kinetic energy cutoff is 100 Ry. 1*1*1 k point sampling is used.

**Comment by hongriTianqi** [comment]
- [x] Reproduce the performance issue on a similar system or environment.
- [x] Identify the specific section of the code causing the performance issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified performance issue.
- [ ] Implement the chosen solution to address the performance issue.
- [ ] Test the implemented solution to ensure it improves performance without introducing new issues.
- [ ] Optimize the solution if necessary, considering trade-offs between performance and other factors (e.g., code complexity, readability, maintainability).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Merge the improved solution into the main codebase and notify the issue reporter.

**Comment by hongriTianqi** [comment]
- [ ] Identify the specific code file or section with the code quality issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified issue.
- [ ] Refactor the code to improve code quality, following the suggested solution.
- [ ] Ensure the refactored code adheres to the project's coding standards.
- [ ] Test the refactored code to ensure it functions as expected.
- [ ] Update any relevant documentation, if necessary.
- [ ] Submit a pull request with the refactored code and a description of the changes made.

**Comment by Liu-RX** [comment]
We carried out more tests with the example case. Now, the reason becomes clear. First, the `to_wannier90` function costs much more time than the counterpart function in QE, which is the major reason. Second, the diagonalization threshold in ABACUS is set to be the same as QE, which is 0.1*scf_thr/nelectron. The default scf_thr is 1e-6 for QE and 1e-9 for ABACUS. Third, the ABACUS uses `cg` rather than `dav` as the default diagonalization method. `dav` is much faster than `cg` in this case. If `scf_thr` is set to the same number and `dav` is used, the pure NSCF calculation is as fast as the QE.

**Comment by Liu-RX** [comment]
The threshold problem is solved by PR #2926

**Comment by Liu-RX** [comment]
The Mmn efficiency problem is solved by PR #2961

**Comment by Liu-RX** [comment]
UNK write problem is solved by #3036
