### ISSUE TITLE
How to define the starting magnetic moments for each atom?

### ISSUE THREAD

**Issue by mohanchen** [deepmodeling/abacus-develop#293]
**Is your feature request related to a problem? Please describe.**
We need to have a CONVENIENT setup for the starting magnetic moments for each atom.

**Describe the solution you'd like**
Maybe an array in the input file to setup the starting magnetic moments. 

**Describe alternatives you've considered**
Otherwise, we can specify the magnetic moments in the STRU file.

**Additional context**
We need someone to implement this feature and related initialization.

**Comment by DYang90** [comment]
There are 3 input structures could be considered.
1、symbol='Ni',magmom=2,...<\n>symbol='Ni',magmom=-2,...<\n>symbol='O',magmom=0,...<\n>symbol='O',magmom=0,...
2、symbol='Ni Ni O O', <\n>magmom='2 -2 2*0',<\n>....
3、symbol='Ni1',magmom=2,...<\n>symbol='Ni2',magmom=-2,...<\n>symbol='O',magmom=0,...
The second one might be suitable for manual inputs，because some values of magmom can be abbreviated as ntype*magmom.
The last one is more complex because a number is always needed for classifying the atoms with magnetic moments and Hubbard parameters, eg. symbol='Co Co Co Co...',magmom='2*3 2*2...' ldauu='4.5 3.0 4.5 3.0'=>symbol='Co1',magmom=3,ldauu=4.5...<\n>symbol='Co2',magmom=3,ldauu=3.0...<\n>symbol='Co3',magmom=2,ldauu=4.5...<\n>symbol='Co4',magmom=2,ldauu=3.0...<\n>... :-(

**Comment by DYang90** [comment]
**There are 3 input structures could be considered.**
1.
symbol='Ni',magmom=2,...
symbol='Ni',magmom=-2,...
symbol='O',magmom=0,...
symbol='O',magmom=0,...
2.
symbol='Ni Ni O O', 
magmom='2 -2 2*0',
....
3.
symbol='Ni1',magmom=2,...
symbol='Ni2',magmom=-2,...
symbol='O',magmom=0,...

**The second one might be suitable for manual inputs，because some values of magmom can be abbreviated as ntype*magmom.
The last one is more complex because a number is always needed for classifying the atoms with magnetic moments and Hubbard parameters, eg.** 
symbol='Co Co Co Co...',
magmom='2*3 2*2...',
ldauu='4.5 3.0 4.5 3.0...'
...
=>
symbol='Co1',magmom=3,ldauu=4.5...
symbol='Co2',magmom=3,ldauu=3.0...
symbol='Co3',magmom=2,ldauu=4.5...
symbol='Co4',magmom=2,ldauu=3.0...
...

**Comment by mohanchen** [comment]
OK, we will try to update the function.

**Comment by DYang90** [comment]
> OK, we will try to update the function.
I suggest that the magnetic moments should be specified in the STRU file. In this way, we can edit the magnetic moments in STRU file by some visualizer tools.

**Comment by ZhouGD2000** [comment]
I use the second structure suggested by @DYang90, which is also used in VASP,  but also preserve the original way.
The input struture is
```
magmom m1  m2 n3*m3 
```
where m1,m2,m3,....following the same order as the atom  type in STRU file, and is defined in INPUT file. There must be NO space before and after *.

Either defining the magnetic moment in this way  or in STRU file is allowed, but not both of them.
NOTICE: this is just a modification in the input structure.

**Comment by DYang90** [comment]
> I use the second structure suggested by @DYang90, which is also used in VASP, but also preserve the original way.
> The input struture is
> 
> ```
> magmom m1  m2 n3*m3 
> ```
> 
> where m1,m2,m3,....following the same order as the atom type in STRU file, and is defined in INPUT file. There must be NO space before and after *.
> 
> Either defining the magnetic moment in this way or in STRU file is allowed, but not both of them.
> NOTICE: this is just a modification in the input structure.

Perhaps some forethought for noncollinear magnetic case is necessary.

**Comment by wenfei-li** [comment]
It seems this issue has been resolved, therefore it will be closed
