### ISSUE TITLE
Different versions have different energies

### ISSUE THREAD

**Issue by sunml99** [deepmodeling/abacus-develop#3014]
### Describe the bug

We found the system energy results calculated with the latest code(v3.3.4) and 
v3.0.0 are very different by ~40 eV. We also tested v3.2.3 and got the same results as v3.0.0. We'd like to know the reason for the energy difference.

Attached is the test system (Pt slab, LCAO basis set).

[case.tar.gz](https://github.com/deepmodeling/abacus-develop/files/12710171/case.tar.gz)

### Task list for Issue attackers

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by jinzx10** [comment]
One possible reason is that we adopt a new two-center integral algorithm in v3.3.4. 

Prior to v3.3.4, two-center integration is calculated with Simpson's rule, which is affected by 4 input parameters (lcao_ecut, lcao_dk, lcao_dr & lcao_rmax). Ideally one should do a convergence analysis on those parameters, i.e., increase lcao_ecut & decrease lcao_dr & lcao_dk to let the calculation reach converged energy. In practice, we found that default values of lcao_dr, dk & rmax are usually fine, but lcao_ecut is not; one often has to explicit set "lcao_ecut" to 1000~2000 in INPUT in order to achieve convergence.

In v3.3.4, the two-center integration algorithm is rewritten to get rid of those parameter dependence. Now lcao_ecut no longer affects standard KS-DFT (it still affect DFT using hybrid functional and dipole calculation, though).

To compare results between v3.2.3 and v3.3.4, we recommend you add "lcao_ecut 2000" to INPUT.

**Comment by sunml99** [comment]
Thanks a lot! I set "lcao_ecut 2000" in v3.2.3 and obtained similar energy results to v3.3.4. Does it mean the previous calculations using the lcao_ecut defaults did not converge? The current version is the accurate one?

**Comment by jinzx10** [comment]
> Thanks a lot! I set "lcao_ecut 2000" in v3.2.3 and obtained similar energy results to v3.3.4. Does it mean the previous calculations using the lcao_ecut defaults did not converge? The current version is the accurate one?

Yes, the default lcao_ecut (which is set to be the same as ecutwfc) is usually too small; very often one has to manually set lcao_ecut to some large number to reach converged results. On the other hand, a large lcao_ecut could lead to performance degradation - especially for small systems. Ideally we would like to have an lcao_ecut that "just adequately large". Unfortunately such ideal lcao_ecut is case-by-case and orbital-dependent; for some calculations 500 is pretty good; for others one needs 2000 or more. To resolve this issue, we introduced an FFT-based algorithm in v3.3.4 and now basic calculation no longer depends on lcao_ecut. The new algorithm can be considered reliable.
