### ISSUE TITLE
The default parameter value in documentation is different from INPUT file after calculation

### ISSUE THREAD

**Issue by ieiue** [deepmodeling/abacus-develop#3240]
### Details

nbands:
https://abacus.deepmodeling.com/en/latest/advanced/input_files/input-main.html#nbands
In documentation, nbands has different formulas for different nspin values. In INPUT file which obtained after calculation, it was zero.
smearing_sigma:
https://abacus.deepmodeling.com/en/latest/advanced/input_files/input-main.html#smearing-sigma
The default value is 0.001 in documentation. I obtained 0.01 in INPUT file. 

### Have you read the online manual http://abacus.deepmodeling.com/en/latest/

- [X] Yes, I have read the online manual.

### Task list for Issue attackers (only for developers)

- [ ] Identify the specific section of the documentation with the issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified issue.
- [ ] Update the documentation to address the issue, following the suggested improvement.
- [ ] Ensure the updated documentation adheres to the project's documentation standards.
- [ ] Test the updated documentation to ensure it is clear and accurate.
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Publish the updated documentation and notify the issue reporter.

**Comment by hongriTianqi** [comment]
This is the same issue as #3239

**Comment by WHUweiqingzhou** [comment]
@ieiue,
Do you mean the parameters in `OUT.suffix/INPUT` is not consistent with the default value?
Please notice that `OUT.suffix/INPUT` contain **the initial default of ABACUS** instead of the real parameters used in calculations. If you want to figure out the real parameters used in calculations, you can open `OUT.suffix/runing_scf.log` and research corresponding parameter you are interested.

Back to your confusion, the initial default of `nband` is 0, while it does not mean 0 is the value used in calculations. 
Maybe we should add a new part to introduce ABACUS's output in documentation. linked with #3311. 
As for `smearing_sigma` should be 0.01, 0.001 is a typo, we will fix it.
