### ISSUE TITLE
Bugs in k-point output caused by kpar

### ISSUE THREAD

**Issue by Chentao168** [deepmodeling/abacus-develop#3244]
### Describe the bug

In scf, nkstot_ibz = 84 and kpar = 4 but `running_scf.log` only shows 21 kpoints such as, 
 21/21 kpoint (Cartesian) = -0.059990 0.0000 0.014997 (963 pws)

### Expected behavior

`running_scf.log` only shows 84 kpoints.

### To Reproduce

[20231122-bug.zip](https://github.com/deepmodeling/abacus-develop/files/13439792/20231122-bug.zip)

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by kirk0830** [comment]
currently `out_alllog 1` would solve this problem. For example if use `example/scf/pw_Si2`, with `kpar 4` and `out_alllog 1`, run with `OMP_NUM_THREADS=1 mpirun -np 12 abacus`, there will be 12 `running_scf_*.log` files in `OUT.ABACUS` directory. Open the 1st, 4th, 7th and 10th log file, you will find:  
![img_v3_0262_1c5dee7b-63ca-47ce-8140-649c98f42ccg](https://github.com/deepmodeling/abacus-develop/assets/67682086/bc0bbadb-4ee8-4ce9-a87a-58c674fb301e)
As reference, see the right, `kpar 1` counterpart. This behavior is, however, as expected, because `GlobalV::ofs_running` only initialized on rank0, if `out_alllog 0`, and vice versa.
![img_v3_0262_1e75b17e-5369-4cfe-a248-f80233bacb4g](https://github.com/deepmodeling/abacus-develop/assets/67682086/fcd5b892-0499-47ea-b0d1-bc28146f92a0)

**Comment by Chentao168** [comment]
I have tried `out_alllog 1` in `example/scf/pw_Si2`. But, only `running_scf_1.log` shows the ' STATE ENERGY(eV) AND OCCUPATIONS    NSPIN == 1' of 2 k-points. The calculation has 8 k-points.
[20231213-kpar.zip](https://github.com/deepmodeling/abacus-develop/files/13660551/20231213-kpar.zip)

**Comment by WHUweiqingzhou** [comment]
@kirk0830,
do you have more suggestion?

**Comment by hongriTianqi** [comment]
This issue has been fixed. The following shows results of the example in examples/scf/pw_Si2 when one sets kpar to 2
<img width="1401" alt="tt" src="https://github.com/user-attachments/assets/9cf771ab-ca09-4ef4-8be5-2f9ea0c88bc8">
