### ISSUE TITLE
PBE calculation in restart HSE spoils converged HSE charge density dumped from last run

### ISSUE THREAD

**Issue by kirk0830** [deepmodeling/abacus-develop#3413]
### Describe the bug

Every time do HSE calculation, PBE calculation will first be performed, however, this procedure will make calculation run into trouble when restarting from even converged charge produced with HSE functional. 
A proper manner may be directly starting HSE iteration in restart run from converged charge.

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by QuantumMisaka** [comment]
@PeizeLin Could you have some view and comments ?

**Comment by PeizeLin** [comment]
> @PeizeLin Could you have some view and comments ?

There are two loop modes for hybrid functionals currently. One way is to first loop GGA, then loop hybrid. Another way is to first loop GGA, then the outer EXX loop and inner GGA loop.
This is because EXX calculations requires density matrix. Now the first loop GGA is used to get the density matrix. 

I think two new loop modes can be introduced: removing the first loop GGA in the above two ways.
Restart can use these modes. The density matrix is read from input.
What's more, the subsequent steps of Relax, MD and Cell-Relax can also use these modes. The density matrix is got from the previous step.

**Comment by WHUweiqingzhou** [comment]
@PeizeLin and @kirk0830,
I also think the restart mode for the calculations which need density matrix should be added into our schedule. Actually, we can try in these two ways:
1. Construct initial density matrix from initial charge density. I have put this idea into Issue #3536 
2. Fix initial charge density unchanged at first several iterations, while update density matrix to find the density matrix corresponding to the initial charge density.
