### ISSUE TITLE
Spin-polarized SCF of H single atom CANNOT converge

### ISSUE THREAD

**Issue by QuantumMisaka** [deepmodeling/abacus-develop#3560]
### Details

[H.tar.gz](https://github.com/deepmodeling/abacus-develop/files/14075071/H.tar.gz)

SCF of a single H atom (in a large cell, gamma-only) CANNOT converge when using `nspin 2` setting. For `nspin 1`, the SCF converge quickly, but surely for this radical system `nspin 2` is needed.

There may be some problem in SCF process. 

### Task list for Issue attackers (only for developers)

- [ ] Reproduce the performance issue on a similar system or environment.
- [ ] Identify the specific section of the code causing the performance issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified performance issue.
- [ ] Implement the chosen solution to address the performance issue.
- [ ] Test the implemented solution to ensure it improves performance without introducing new issues.
- [ ] Optimize the solution if necessary, considering trade-offs between performance and other factors (e.g., code complexity, readability, maintainability).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Merge the improved solution into the main codebase and notify the issue reporter.

**Comment by mohanchen** [comment]
Thanks for the finding, we will look into this issue.

**Comment by YuLiu98** [comment]
I tested the case with abacus v3.2.0, and found that the case can converge successfully. [v3.2.0.tar.gz](https://github.com/deepmodeling/abacus-develop/files/14076925/v3.2.0.tar.gz)

I think the charge mixing for magnetic calculations may not work for the special case.

Can you look into the issue? @Qianruipku @WHUweiqingzhou  Is there some special setting for the case?

**Comment by WHUweiqingzhou** [comment]
@QuantumMisaka and @YuLiu98,
Since new mixing method introduce a new mixing parameter `mixing_beta_mag` $\alpha_m$, whose default value is $4\alpha_{\rho}$. After mixing, we get $\rho_{up}$ and $\rho_{down}$ by:
$$\rho_{up} = \frac{1}{2}(\rho+m),    \rho_{down} = \frac{1}{2}(\rho-m)$$
For this special case H atom, $\rho_{up}=1.0$ while $\rho_{down}=0.0$. If $\alpha_m \ne \alpha_{\rho}$, finite $\rho_{up}$ also results in a finite $\rho_{down}$ by $\rho_{down} = \frac{1}{2}(\rho-m)$.
To avoid this unreal number, we can set $\alpha_m = \alpha_{\rho}$. @QuantumMisaka, you can set `mixing_beta_mag` equal to `mixing_beta`, and make sure `mixing_gg0=mixing_gg0_mag=0.0` also. I believe this problem will be solved.
So, current default $\alpha_m=4\alpha_{\rho}$ may fail for the case where one of $\rho_{up},\rho_{down}$ is finite while the other is exactly zero. I can add some docs to claim it.

**Comment by WHUweiqingzhou** [comment]
@QuantumMisaka and @YuLiu98,
Let us consider this question from a more general perspective. $\alpha_m = \alpha_{\rho}$ mean $\rho_{up}$ and $\rho_{down}$ mix independently from each other, just like old mixing method in version3.4.2. While $\alpha_m \ne \alpha_{\rho}$ means $\rho_{up}$ will be contributed from $\rho_{down}$, vice versa. 
For an atomic system, the $\rho_{up}$ and $\rho_{down}$ of the ground state refers to different Kohn-Sham orbitals. We all know Kohn-Sham orbitals are orthogonal to each other. So the mixture of $\rho_{up}$ and $\rho_{down}$ should be exactly independent, otherwise SCF cannot find the ground state forever.

**Comment by QuantumMisaka** [comment]
@WHUweiqingzhou 
However, in my test using this INPUT setting:
```
INPUT_PARAMETERS RUNNING ABACUS-DFT

#Parameters (1.General)
suffix                  ABACUS  # suffix of OUTPUT DIR
nspin                   2   #  1/2/4 4 for SOC
symmetry                0   #  0/1  1 for open, default
esolver_type            ksdft  # ksdft, ofdft, sdft, tddft, lj, dp
dft_functional          pbe  # same as upf file, can be lda/pbe/scan/hf/pbe0/hse
ks_solver             genelpa  # default for ksdft-lcao

#Parameters (2.Iteration)
calculation             scf # scf relax cell-relax md
ecutwfc                 100   # Rydberg, with pseudopot, lcao use pw for inner part
scf_thr                 1e-7  # drho, Rydberg
scf_nmax                100

#Parameters (3.Basis)
basis_type              lcao  # lcao or pw
# kspacing              0.25 # replace KPT
gamma_only            1  # 0/1, replace KPT

#Parameters (4.Smearing)
smearing_method         mp    # mp/gau/fd/fixed, mp for metal gau for semicon
smearing_sigma          0.002  # Rydberg, 0.002 for mp 0.001 for gau

#Parameters (5.Mixing)
mixing_type             broyden  # pulay/broyden
mixing_beta             0.4  # for metal: 0.05-0.4, 0 - 0.1 for difficult
mixing_beta_mag         0.4
mixing_gg0              0.0  # only for transition metal
mixing_gg0_mag          0.0
#mixing_ndim             20

#Parameters (6.Calculation)

cal_force          1
cal_stress         1
out_stru           1  # print STRU in OUT
out_chg            0  # print CHG or not
out_bandgap        1  # if bandgap and mul out, chg will out
out_mul            1  # print Mulliken charge and mag of atom in mulliken.txt
```
This SCF still cannot converge

For changing mp smearing to gau smearing, convergence also cannot be reached

**Comment by QuantumMisaka** [comment]
> @WHUweiqingzhou However, in my test using this INPUT setting:
> 
> ```
> INPUT_PARAMETERS RUNNING ABACUS-DFT
> 
> #Parameters (1.General)
> suffix                  ABACUS  # suffix of OUTPUT DIR
> nspin                   2   #  1/2/4 4 for SOC
> symmetry                0   #  0/1  1 for open, default
> esolver_type            ksdft  # ksdft, ofdft, sdft, tddft, lj, dp
> dft_functional          pbe  # same as upf file, can be lda/pbe/scan/hf/pbe0/hse
> ks_solver             genelpa  # default for ksdft-lcao
> 
> #Parameters (2.Iteration)
> calculation             scf # scf relax cell-relax md
> ecutwfc                 100   # Rydberg, with pseudopot, lcao use pw for inner part
> scf_thr                 1e-7  # drho, Rydberg
> scf_nmax                100
> 
> #Parameters (3.Basis)
> basis_type              lcao  # lcao or pw
> # kspacing              0.25 # replace KPT
> gamma_only            1  # 0/1, replace KPT
> 
> #Parameters (4.Smearing)
> smearing_method         mp    # mp/gau/fd/fixed, mp for metal gau for semicon
> smearing_sigma          0.002  # Rydberg, 0.002 for mp 0.001 for gau
> 
> #Parameters (5.Mixing)
> mixing_type             broyden  # pulay/broyden
> mixing_beta             0.4  # for metal: 0.05-0.4, 0 - 0.1 for difficult
> mixing_beta_mag         0.4
> mixing_gg0              0.0  # only for transition metal
> mixing_gg0_mag          0.0
> #mixing_ndim             20
> 
> #Parameters (6.Calculation)
> 
> cal_force          1
> cal_stress         1
> out_stru           1  # print STRU in OUT
> out_chg            0  # print CHG or not
> out_bandgap        1  # if bandgap and mul out, chg will out
> out_mul            1  # print Mulliken charge and mag of atom in mulliken.txt
> ```
> 
> This SCF still cannot converge
> 
> For changing mp smearing to gau smearing, convergence also cannot be reached

Solved, there is a setting problem in STRU, set initial magnetic moment to 1 will get proper result and SCF will converge in 7 steps
