### ISSUE TITLE
The 'bndpar' variable  can't read properly from INPUT file

### ISSUE THREAD

**Issue by jiongwalai** [deepmodeling/abacus-develop#3580]
### Describe the bug

The 'bndpar' variable was set as 2 in INPUT file. But this variable shown in INPUT file in the folder OUT.suffix was 1.

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by WHUweiqingzhou** [comment]
@jiongwalai,

For your case, 
```cpp
    if (esolver_type != "sdft")
        bndpar = 1;
```
`bndpar` will be reset to 1 for non-sdft calculations though you set it.

Actually,
> OUT.suffix/INPUT contain the initial default of ABACUS instead of the real parameters used in calculations. If you want to figure out the real parameters used in calculations, you can open OUT.suffix/runing_scf.log and research corresponding parameter you are interested.

you can see it in https://abacus.deepmodeling.com/en/latest/quick_start/output.html#input
At the very beginning, we offer `OUT.suffix/INPUT` to reproduce results since the default value of parameter changes for different version. 
Sorry for your misunderstanding. We will think how to avoid it.

@mohanchen @dyzheng 
Should we change `OUT.suffix/INPUT` or just leave it? This issue is not the first one to complain this file, also see #3240 .

**Comment by jiongwalai** [comment]
@WHUweiqingzhou Thanks for answering.
In VASP software, the parallel computing of bands controlled by 'NPAR' has significantly improved the efficiency. I am wondering if it supports ksdft calculation in future development.

**Comment by WHUweiqingzhou** [comment]
> @WHUweiqingzhou Thanks for answering. In VASP software, the parallel computing of bands controlled by 'NPAR' has significantly improved the efficiency. I am wondering if it supports ksdft calculation in future development.

@Qianruipku, do you have any comment about this?

**Comment by WHUweiqingzhou** [comment]
In principle, `bndpar` can be used to accelerate the calculations. However, ABACUS has not supported this parallel strategy yet.
We will consider adding this feature in the future, maybe this year.
