### ISSUE TITLE
BFGS in ABACUS is incorrect

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#3600]
### Describe the bug

I have tested the relax of some examples  by using BFGS method in ABACUS and by BFGS method in ASE (calculator is abacus). The energy curve by using ABACUS cannot slowly decrease like the energy curve of ASE.

one example 002_pt111 is:
ASE+ABACUS:
![68252f428b6b65630d5ea09fb205befd_c679b7ab-59d1-405b-9bf0-138ad1d1d5b9](https://github.com/deepmodeling/abacus-develop/assets/91927439/adad3f78-7962-46ad-9b6e-ce954843a5fd)

ABACUS:
![ac7709ab1be771df4d6b5e8724cffa95_viSzAcSow9gAAAABJRU5ErkJggg==](https://github.com/deepmodeling/abacus-develop/assets/91927439/a31de1f9-6ea3-48d8-8594-13ddf5ae8049)

Also have tested the code of https://github.com/sunliang98/abacus-develop/tree/hot-fix:
![002_pt111](https://github.com/deepmodeling/abacus-develop/assets/91927439/5ad58980-552e-4877-905b-1031d741c137)

More results are shown in: https://dptechnology.feishu.cn/docx/KmqbdUFP4oi6nyxbW8Jc8l5knff
[bfgs.zip](https://github.com/deepmodeling/abacus-develop/files/14160361/bfgs.zip)

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by WHUweiqingzhou** [comment]
Hi, @mohanchen and @sunliang98,
here are some Tests about BFGS from @pxlxingliang.

**Comment by sunliang98** [comment]
I have repeated the above example, but I found that the second and third picture displays the ETOT DIFF, not total energy as labeled on y axes, the true energy curve of ABACUS is shown below:
![image](https://github.com/deepmodeling/abacus-develop/assets/50293369/30627e96-1b20-402f-8a86-47cf37088023)
Besides, I notice that the origin of the ASE energy curve is 0 eV, different from 82.36 eV of ABACUS, so I wonder how does ASE read the energy from ABACUS? By the way, could you @pxlxingliang please upload the examples of ASE, so that I could compare the results of ASE and ABACUS?

**Comment by pxlxingliang** [comment]
@sunliang98 Sorry, the ETOT DIFF is my mistake.

The energy in the image is shifted to let the energy of initial structure is 0.

I have upload a script in https://dptechnology.feishu.cn/docx/KmqbdUFP4oi6nyxbW8Jc8l5knff. You can download it to run ase+abacus to do relax. You should notice that if you want to use esolver lj, you need to modify ASE, because the original codes can only deal with the cases on esolver  ksdft.

**Comment by pxlxingliang** [comment]
I found that the update of pos (atom position of current step) in `setup_gradient()` is from atom, and the atomic coordinates in the class will always check if the position of atom is in the box, and this will may lead to that some atom may has a big position movement.

https://github.com/deepmodeling/abacus-develop/blob/develop/source/module_relax/relax_old/ions_move_basic.cpp#L25-L50

If set the value of pos in setup_gradient() only in the first relax step, the energy cure of example 002 is:
![af810082a66c3c0f9d10b35c5319aef0__preview_type=16](https://github.com/deepmodeling/abacus-develop/assets/91927439/ff17b594-6c9d-4392-a1a9-3c2d05ec3cba)

**Comment by sunliang98** [comment]
It really works, and replacing the 'if' of `module_cell/unitcell.cpp` line 445-455 with 'while' will help to avoid warning quit.
With above update, the energy curve of 007 example obtained by ABACUS becomes:
![image](https://github.com/deepmodeling/abacus-develop/assets/50293369/1dcd027e-25e5-4cdc-9b7b-e04fcec1efc8)
I further update the algorithm according to the ASE, the codes can be found [here](https://github.com/sunliang98/abacus-develop/tree/hot-fix), the energy curve of 007 becomes:
![image](https://github.com/deepmodeling/abacus-develop/assets/50293369/4345f60b-d640-4e06-856e-faa079dc331f)
The performance is improved, but still worse than ASE:
![image](https://github.com/deepmodeling/abacus-develop/assets/50293369/a23d938f-940d-49a3-8827-f308e15ccc70)

**Comment by pxlxingliang** [comment]
Hi, @sunliang98 What "warning quit"?

**Comment by pxlxingliang** [comment]
I test more examples,

  | ASE | ABACUS（old version） |  ABACUS（fix the large move bug）
-- | -- | -- | --
000_CO-Fe5C2 |![a1077f0fd89cd6c0ed85508ff6b7493f__fallback_source=1 height=1280 mount_node_token=Xcslde6nBopUIxx1qoCcJS3HnHd mount_point=docx_image policy=equal width=1280](https://github.com/deepmodeling/abacus-develop/assets/91927439/bef7a7aa-cc43-42bf-bef1-df78720b71e7)| ![e89ba9e144ca0a56a3bd5b8129eab41e__fallback_source=1 height=1280 mount_node_token=NZv7dBbijoOM30xcyYicDBvUnUh mount_point=docx_image policy=equal width=1280](https://github.com/deepmodeling/abacus-develop/assets/91927439/8cb52d28-4513-4611-9ddf-138f897178ba) |   ![956cd8b99cc65eababb697b2200be918_hhCDwAAAEBF2OgBAAAAqAihBwAAAKAihB4AAACAihB6AAAAACpC6AEAAACoCKEHAAAAoCKEHgAAAICKEHoAAAAAKkLoAQAAAKgIoQcAAACgIv4Gip7gvl4grDkAAAAASUVORK5CYII=](https://github.com/deepmodeling/abacus-develop/assets/91927439/cb14c611-be73-4c63-9096-a6919374c8b9)
001_lisi |![c0acd2f1fd58b21e13da5b601aac3654__fallback_source=1 height=1280 mount_node_token=LZbCdy4iioTDXUxNo06cuFIdnze mount_point=docx_image policy=equal width=1280](https://github.com/deepmodeling/abacus-develop/assets/91927439/a74bce6d-e06c-4945-adbd-ec742a72d765) |![5ed064db1c582ded3e718a592e7cf701__fallback_source=1 height=1280 mount_node_token=B9phdfgkIo8U89xX3y5c2Afln6c mount_point=docx_image policy=equal width=1280](https://github.com/deepmodeling/abacus-develop/assets/91927439/08b27189-bf97-426b-be0a-8ede4476ca77)|![a05b43d67e3760a129dfe53b6437daa9_Vaq0JPADAq8QdAAAAgMRs7gAAAAAkJu4AAAAAJCbuAAAAACQm7gAAAAAkJu4AAAAAJCbuAAAAACR2AYBYfFKrq9cfAAAAAElFTkSuQmCC](https://github.com/deepmodeling/abacus-develop/assets/91927439/a96ad92e-15b9-4551-b842-aa0149f077ba)  
002_pt111 |![b5a3446d8a8c5d077784a5f9c09f0379__fallback_source=1 height=1280 mount_node_token=KlE8dSU72o6zSMxljpccUKXOnag mount_point=docx_image policy=equal width=1280](https://github.com/deepmodeling/abacus-develop/assets/91927439/8005a1df-8578-4433-b5f1-99f04cd2300e) |![cf9f4ecf28216bc2f3ab4c8ea89d296e__fallback_source=1 height=1280 mount_node_token=PdTLdrhQfobidsxPyk7c2Z2Enhr mount_point=docx_image policy=equal width=1280](https://github.com/deepmodeling/abacus-develop/assets/91927439/0ccb9102-8363-426a-845a-93144a84e36e) |  ![379b314655a934b58e5bf3fbf1895931__fallback_source=1 height=1280 mount_node_token=KZ5IdAybTodt1BxzQILclDKSnFg mount_point=docx_image policy=equal width=1280](https://github.com/deepmodeling/abacus-develop/assets/91927439/fc0a7c55-d3d2-4e6e-a58a-e95eb0e5d262)  
003_InSe |![df1f243dda3989157ca912f49e80a386_FAAAAABJRU5ErkJggg==](https://github.com/deepmodeling/abacus-develop/assets/91927439/7ea11fde-e333-4fd4-b029-5ae195f9705f) | ![14468cabf373589b8a79389627395ae0_wceoz65aoL1WgAAAABJRU5ErkJggg==](https://github.com/deepmodeling/abacus-develop/assets/91927439/83f6a826-99f7-488d-91b8-20cf25aba82e)|![ae621ea65b7f328686b18b4340b44b12_weN18GAT+hzMQAAAABJRU5ErkJggg==](https://github.com/deepmodeling/abacus-develop/assets/91927439/4be3528f-8c27-4238-b34f-39692145157e)  
004_ZrO2-doped-Si-cell |![4c8661a5f9b63b0c45e613be7c3ea8ad__fallback_source=1 height=1280 mount_node_token=MxlqdS0QfoSod7x1H08cNWjrnqU mount_point=docx_image policy=equal width=1280](https://github.com/deepmodeling/abacus-develop/assets/91927439/89dd8ca9-106e-4916-8d00-f0b2655fbe88)| ![d34880298674a8843b42c42f820f5737__fallback_source=1 height=1280 mount_node_token=VCaRdMamVoBKs7xrWYacH6YUnwc mount_point=docx_image policy=equal width=1280](https://github.com/deepmodeling/abacus-develop/assets/91927439/f6b6a793-f2d0-44e6-82a4-49b1de01a017)| ![607a470d8c56c827e40b6fa54f46a48f__fallback_source=1 height=1280 mount_node_token=F6lOdtSB4oTFmhxka8zcOZSCnUf mount_point=docx_image policy=equal width=1280](https://github.com/deepmodeling/abacus-develop/assets/91927439/15e49da2-1223-4ea7-a3fb-a2484738b6f8)  
005_HSiNMoS |![cee8bf446c187bc34d744ba107cc36f7__fallback_source=1 height=1280 mount_node_token=TeovdWITJoWP9hxuL4ac6ZuqnRc mount_point=docx_image policy=equal width=1280](https://github.com/deepmodeling/abacus-develop/assets/91927439/9bf6251b-ef0e-44c3-9eff-463c611a2d8b)| ![6224f53757edf290ac351ff6c37fb4b2__fallback_source=1 height=1280 mount_node_token=Jga6dR5kvo3ajOxA7ozc72efnyb mount_point=docx_image policy=equal width=1280](https://github.com/deepmodeling/abacus-develop/assets/91927439/67f8ca96-9e90-4daa-b8d8-7ed434feb4f4)| ![648f56304b92c1bf4c897bbc76bf2d2a_vlwCOEEIIITaQ4I0QQgghhBBCCCHEFiY5b4QQQgghhBBCCCG2MAneCCGEEEIIIYQQQmxhErwRQgghhBBCCCGE2ML+f28L7VYj4wWpAAAAAElFTkSuQmCC](https://github.com/deepmodeling/abacus-develop/assets/91927439/3816a4d5-fe59-42b0-8933-d251cc191c15) 
007_graphene | ![e4d51bf7e1ec0960d0be9d9028266eac__fallback_source=1 height=1280 mount_node_token=ONdZd56zloXxBWxEOBXcAgIwnOg mount_point=docx_image policy=equal width=1280](https://github.com/deepmodeling/abacus-develop/assets/91927439/572fc3c9-f052-4877-99f1-856005bcde70)| ![1498376bf3a5368187c5c6511e38735f__fallback_source=1 height=1280 mount_node_token=DRuFdiMBjoLKKFxPQKfclYAfntd mount_point=docx_image policy=equal width=1280](https://github.com/deepmodeling/abacus-develop/assets/91927439/cb62326f-4869-4f36-8452-b62217d2b36e) | ![image](https://github.com/deepmodeling/abacus-develop/assets/91927439/5726139c-af8c-441f-a6ae-edbf06a5cd69)  

[bfgs.zip](https://github.com/deepmodeling/abacus-develop/files/14441802/bfgs.zip)

**Comment by pxlxingliang** [comment]
After fix the large move bug, all examples have the energy gradually decreasing, and the energy curve of ASE and ABACUS(fix bug)  are similar except for 004 and 007.
For 004, it seems that abacus a lower state.

**Comment by pxlxingliang** [comment]
The method to update atomic movement are different in the BFGS in ASE and ABACUS.
ASE actually only calculates the direction of atomic movement (`-H^-1 * g`) and directly uses this value as the size of the movement (except that if the maximum movement distance is greater than the set maxstep, reducing the movement to make the maximum movement distance being maxstep).
ABACUS use the trust region method to find the move direction.

**Comment by sunliang98** [comment]
> Hi, @sunliang98 What "warning quit"?

![image](https://github.com/deepmodeling/abacus-develop/assets/50293369/2cca51f8-9a54-42f3-9552-9852093fee3b)
In the function `Ions_Move_Basic::move_atoms`, ABACUS will call `update_pos_tau(pos)` to set `atom->tau = pos/lat0`, and then the function `periodic_boundary_adjustment` will be called. Since we do not update the `Ions_Move_BFGS::pos` in `setup_gradient`, the change of `Ions_Move_BFGS::pos` will be accumulated, and when the change of the `Ions_Move_BFGS::pos` is larger than the length of cell, then warning quit displayed in above figure will be triggered.

**Comment by pxlxingliang** [comment]
> > Hi, @sunliang98 What "warning quit"?
> 
> In the function `Ions_Move_Basic::move_atoms`, ABACUS will call `update_pos_tau(pos)` to set `atom->tau = pos/lat0`, and then the function `periodic_boundary_adjustment` will be called. Since we do not update the `Ions_Move_BFGS::pos` in `setup_gradient`, the change of `Ions_Move_BFGS::pos` will be accumulated, and when the change of the `Ions_Move_BFGS::pos` is larger than the length of cell, then warning quit displayed in above figure will be triggered.

Ok, I see. Thanks! 

Maybe we should keep this check, and there should not has a large movement in relax?

**Comment by sunliang98** [comment]
I have updated the algorithm of BFGS by
I. Correction
1. `grad = - force`, instead of `grad = - force * lat0`. (line 52 of module_relax/relax_old/ions_move_basic.cpp)
2. correct the formula of `trust_radius`. (line 223 of module_relax/relax_old/ions_move_bfgs.cpp)

II. Optimization
1. optimize the initial guess of `inv_hess` accoring to ASE. (line 195 of module_relax/relax_old/bfgs_basic.cpp)
2. optimize the scaling of `move`. (line 303-322 of module_relax/relax_old/ions_move_bfgs.cpp)

The latest code can be found [here](https://github.com/sunliang98/abacus-develop/tree/bfgs).
The results obtained by updated ABACUS are displayed below.

|| ASE | ABACUS (fix the large move bug) | ABACUS (update the algorithm) |
|-------|-------|-------|-------|
|000_CO-Fe5C2| ![image](https://github.com/deepmodeling/abacus-develop/assets/50293369/77791f5a-1c55-49dc-ae81-16cd943c83f0)| ![image](https://github.com/deepmodeling/abacus-develop/assets/50293369/955a769e-e161-46df-8344-f03af438ed90) | ![image](https://github.com/deepmodeling/abacus-develop/assets/50293369/837592cc-09eb-432b-9beb-1ebed4d1f91e) |
|001_lisi| ![image](https://github.com/deepmodeling/abacus-develop/assets/50293369/600ff4bb-73f9-46b0-a8c2-9ae5187ab190) | ![image](https://github.com/deepmodeling/abacus-develop/assets/50293369/bc5f32de-296b-421d-99c0-6e4d7f088921)| ![image](https://github.com/deepmodeling/abacus-develop/assets/50293369/f20aed56-46a2-48d6-85c4-9d5576ec8ae6) |
|002_pt111| ![image](https://github.com/deepmodeling/abacus-develop/assets/50293369/0862a1bd-3deb-4546-9c9b-babb4a370456) | ![image](https://github.com/deepmodeling/abacus-develop/assets/50293369/61e324f6-db80-4268-809c-ed3a4a6dd570) | ![image](https://github.com/deepmodeling/abacus-develop/assets/50293369/c87ccbf5-542b-4891-91b5-7e28080e8021) |
|004_ZrO2-doped-Si-cell| ![image](https://github.com/deepmodeling/abacus-develop/assets/50293369/3c89e19d-363f-408d-a22e-f05a36d7d196) | ![image](https://github.com/deepmodeling/abacus-develop/assets/50293369/b8532b79-2f1a-41d0-a30f-2632942ffba0)| ![image](https://github.com/deepmodeling/abacus-develop/assets/50293369/3755c2b2-52b0-4602-a8e4-7f59a0fa5ff6) |
|005_HSiNMoS| ![image](https://github.com/deepmodeling/abacus-develop/assets/50293369/5f5a6883-75ff-4747-945d-e2a4420aa0a1) | ![image](https://github.com/deepmodeling/abacus-develop/assets/50293369/17d2766b-6cde-430f-9ee1-1b292dc0525a) | ![image](https://github.com/deepmodeling/abacus-develop/assets/50293369/e4b0858f-45b7-4489-a177-803654ebe3e3) |
|007_graphene| ![image](https://github.com/deepmodeling/abacus-develop/assets/50293369/1919b63d-463d-4bd9-a1f0-2dec655cf22b) | ![image](https://github.com/deepmodeling/abacus-develop/assets/50293369/ecdf7033-28d3-4c03-9dff-afb6b7faf13e) | ![image](https://github.com/deepmodeling/abacus-develop/assets/50293369/faf2f04b-693d-4672-838a-d04e37e4dfde) |

Updated ABACUS is more efficient than old-version in most cases, and in 004 and 007, it is more efficient than ASE.
However, in 001 and 002, updated ABACUS seems to be less efficient than old version.
In order to confirm whether above updates are valid, we need more tests, could you @pxlxingliang please to test the updated code in more systems and compare the results to old version? Or could you send me some representative systems? Thank you.

**Comment by WHUweiqingzhou** [comment]
Current BFGS is correct after PR #3658.
