### ISSUE TITLE
Bug: the output of overlap matrix and Hamiltonian matrix should be consistent

### ISSUE THREAD

**Issue by WHUweiqingzhou** [deepmodeling/abacus-develop#3691]
### Describe the bug

The size of output of overlap matrix and Hamiltonian matrix is different, which may result in bug for DeepH. Please make them consistent.

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by iduygnay** [comment]
The situation is I used DeepH to train the bilayer 2D bismuth, I added VDW, dipole correction, and SOC, functionals are PBE and HSE06. Please see the attached file of my INPUT. The output files need to be transferred to hamiltonian.h5 file. In this case, it is a 50x50 matrix. 
![0e04d1fcc70742507be166090a5ab84](https://github.com/deepmodeling/abacus-develop/assets/109792836/6998cd0e-813f-46a2-9d34-51c53f90b0b2)
Then DeepH will use hamiltonian.h5 to train a model. 
For the final step, it needs abacus get_S calculation to give a overlaps.h5 file, but here, the DeepH developer said that I could not turn on any spin polarization or SOC, so I turned them off. This is because if I turn on that, the matrix elements will include an imaginary part, but the overlap matrix should be real only. Then I got a 25x25 matrix.
![30f13c280d06339c2469d8d01e0f098](https://github.com/deepmodeling/abacus-develop/assets/109792836/5ff4a8a4-3fda-4a22-81ed-ad1ad0950595)
The DeepH needs to use the overlaps.h5 file to give a predicted hamiltonian.h5 file. So these two should be the same size. I think overlaps.h5 should be 50x50. 

[Uploading INPUT.zip…]()

**Comment by dyzheng** [comment]
Hello，@iduygnay have you solved this Issue? 
Can you upload your useful script to help other users?

**Comment by iduygnay** [comment]
When we do the inference step in DeepH, the spin-polarized case and SOC case will be recognized as spin=1 since overlaps.h5 is calculated without spin>1. So in these cases, we can just modify the "isspinful" in info.json to "true" would be OK.
