### ISSUE TITLE
large system get_S calculation error report

### ISSUE THREAD

**Issue by iduygnay** [deepmodeling/abacus-develop#3838]
### Describe the bug

[issue.zip](https://github.com/deepmodeling/abacus-develop/files/14788284/issue.zip)
I also tried the 2900atoms calculation, settings like this is enough. 
![image](https://github.com/deepmodeling/abacus-develop/assets/109792836/977f20aa-785c-40e3-b1f7-a4031230a104)
I think 1500G must be enough for 6000+ atoms. So there might be some issue with my other settings. 

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by LiuXiaohui123321** [comment]
I noticed that you are using 1mpi x 32omp parallelism here. But due to the large size of this system and the total number of orbital basis, this parallelism can lead to some parts of the parallelism being insufficient (such as 2D block parallelism) and thus reporting the above error. Please try increasing the number of mpi processes, such as 32. In addition, if you use mpi parallelism, the `nbands` parameter in the INPUT file needs to be adjusted, such as 100.

**Comment by iduygnay** [comment]
> I noticed that you are using 1mpi x 32omp parallelism here. But due to the large size of this system and the total number of orbital basis, this parallelism can lead to some parts of the parallelism being insufficient (such as 2D block parallelism) and thus reporting the above error. Please try increasing the number of mpi processes, such as 32. In addition, if you use mpi parallelism, the `nbands` parameter in the INPUT file needs to be adjusted, such as 100.

This can solve the issue. Thanks!
