### ISSUE TITLE
Test: Integration testing currently doesn't support GPU

### ISSUE THREAD

**Issue by dzzz2001** [deepmodeling/abacus-develop#4033]
### Describe the Testing Issue

I want to add some integrated testing cases for the newly added CUDA code in module_gint, but it seems the version of the abacus used for automated testing does not support CUDA.
![img_v3_02a4_d41cec86-b6dc-4fbb-9a23-83549453df1g](https://github.com/deepmodeling/abacus-develop/assets/153698752/92464d22-4d54-4ca2-8ce4-3f4f688481b3)

### Task list for Issue attackers (only for developers)

- [ ] Understand the testing issue described by the developer.
- [ ] Review the specific test case, expected and actual results, and any error messages.
- [ ] Identify the root cause of the test failure or issue.
- [ ] If a possible solution is suggested, evaluate its feasibility and effectiveness.
- [ ] Implement a fix for the test failure or issue, or create a new test case if needed.
- [ ] Verify that the fix resolves the testing issue and the test case passes.
- [ ] Review and update any relevant documentation, such as test plans or user guides.
- [ ] Ensure the testing issue is resolved and close the ticket.
- [ ] Share any lessons learned or best practices with the team to prevent similar issues in the future.

**Comment by caic99** [comment]
@dzzz2001 Please see #4032, you may add tests in that test config.

**Comment by dzzz2001** [comment]
The purpose of adding new integration test cases is to ensure that the GPU code within module_gint run correctly every time a PR is made, so modifications may be required in the test.yml file as well to provide GPU support.

> @dzzz2001 Please see #4032, you may add tests in that test config.

**Comment by caic99** [comment]
@dzzz2001 You can propose your modifications by PR

**Comment by haozhihan** [comment]
Next, we need to solve #4043 and add GPU integration tests in the `tests` folder so that GPU-related integration tests can work in CI. @dzzz2001

**Comment by dzzz2001** [comment]
I'm not quite clear on how to modify the test.yml to provide the GPU support, could you help me modify the code?

> @dzzz2001 You can propose your modifications by PR

**Comment by caic99** [comment]
> I'm not quite clear on how to modify the test.yml to provide the GPU support, could you help me modify the code?
> 
> > @dzzz2001 You can propose your modifications by PR

Hi @dzzz2001 ,
You may following the steps below:
1. Add test cases into a file, like https://github.com/deepmodeling/abacus-develop/blob/develop/tests/integrate/CASES but with a different name
2. Build and install ABACUS with GPU support, and use `Autotest.sh` with -r flag to launch GPU test cases (see https://github.com/deepmodeling/abacus-develop/blob/develop/tests/integrate/Autotest.sh#L26)
3. Add the script you used in previous step in [.github/workflows/cuda.yml](https://github.com/deepmodeling/abacus-develop/blob/develop/.github/workflows/cuda.yml)
4. If you wish to run tests on every PR, add "on: pull_request" statement in that file.

Notice that there's no need to modify the existing test cases, since using a GPU runner to execute all tests is an overkill.
Please let me know if there's anything to be clarified.
P.S. It would be better to @ somebody on reply, otherwise they won't receive notifications.

**Comment by caic99** [comment]
> Hi @dzzz2001 , You may following the steps below:
> 
> 1. Add test cases into a file, like https://github.com/deepmodeling/abacus-develop/blob/develop/tests/integrate/CASES but with a different name
> 2. Build and install ABACUS with GPU support, and use `Autotest.sh` with -r flag to launch GPU test cases (see https://github.com/deepmodeling/abacus-develop/blob/develop/tests/integrate/Autotest.sh#L26)
> 3. Add the script you used in previous step in [.github/workflows/cuda.yml](https://github.com/deepmodeling/abacus-develop/blob/develop/.github/workflows/cuda.yml)
> 4. If you wish to run tests on every PR, add "on: pull_request" statement in that file.

@haozhihan @denghuilu You could follow the steps above if you want to add more GPU test cases, FYI.
