### ISSUE TITLE
Good Pseudopotentials and orbitals are needed for the element Gd (How to choose pseudopotential from ABACUS Pseudopot-Nao Square)

### ISSUE THREAD

**Issue by hongriTianqi** [deepmodeling/abacus-develop#4120]
### Background

I checked https://[kirk0830.github.io/ABACUS-Pseudopot-Nao-Square/pseudopotential/results/2024-04-30/Gd.html](https://kirk0830.github.io/ABACUS-Pseudopot-Nao-Square/pseudopotential/results/2024-04-30/Gd.html)

Thanks for @kirk0830 

### Describe the solution you'd like

I will generate and test orbitals for this element.

### Task list only for developers

- [ ] Notice possible changes of behavior
- [ ] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Task list for Issue attackers (only for developers)

- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by kirk0830** [comment]
Unfortunately for Gd, none of norm-conserving pseudopotential works well in Gd metallic crystal EOS test, this is because metallic crystal may explicitly need the valence treatment of semicore or near-core electrons, but ecutwfc would be extremely high for pseudopotential with f electrons.
Based on this, two kinds of pseudopotentials are here:
- for those whose names with "f--core" and "3plus", are constructed based on ionic state, and f-electrons NOT VALENCE TREATED, so deficit in metallic bond description
- for the rest, GTH_POTENTIALS_LnPP1 explicitly treat f-electron, similarly the PD04(sp), need high ecutwfc because they are very rigid/hard.

Here is the file of PD04(sp), good luck:
[Gd-sp.PD04.PBE.zip](https://github.com/deepmodeling/abacus-develop/files/15246107/Gd-sp.PD04.PBE.zip)
