### ISSUE TITLE
Computational Time Problems in SCF Calculations Using PBE functional and LDA functional

### ISSUE THREAD

**Issue by yycx1111** [deepmodeling/abacus-develop#4177]
### Describe the bug

1. I was doing SCF calculation on GaN systems and found that the time taken for calculations using LDA functional and PBE functional is equal, the energies are not the same.
2. Shouldn't the LDA functional be more efficient than the PBE functional for SCF calculation and less accurate? Because in the case of a single water molecule deepks training, comparing the computation time and energy of SCF calculation using LDA and PBE, the result is that LDA is more efficient but less accurate.
4. Is the efficiency of the functional related to the calculation system?
The following are input files.
[STRU.txt](https://github.com/deepmodeling/abacus-develop/files/15336682/STRU.txt)
[INPUT.txt](https://github.com/deepmodeling/abacus-develop/files/15336683/INPUT.txt)
[KPT.txt](https://github.com/deepmodeling/abacus-develop/files/15336685/KPT.txt)

### Expected behavior

The time taken to do the SCF calculation using the LDA functional should be shorter than the time taken to do the SCF calculation using the PBE functional.

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by WHUweiqingzhou** [comment]
@yycx1111,

1. PBE only requires additional computation for the partial derivatives of the density compared to LDA, which is not time-consuming. Therefore, it is reasonable that the computation time between LDA and PBE is not much different.

2. Generally speaking, PBE is more accurate than LDA, but this is not absolute. Sometimes LDA might yield better results due to error cancellation. Also, please make sure to keep pseudopotentials and functionals consistent. Using pseudopotentials generated with the LDA functional in combination with PBE might lead to worse results.

3. The computational demand for functionals is related to system size. However, because both LDA and PBE require minimal computation, the difference is not significant. But when considering meta-GGA or hybrid functionals, the computational load will increase significantly.

**Comment by yycx1111** [comment]
> @yycx1111,
> 
> 1. PBE only requires additional computation for the partial derivatives of the density compared to LDA, which is not time-consuming. Therefore, it is reasonable that the computation time between LDA and PBE is not much different.
> 2. Generally speaking, PBE is more accurate than LDA, but this is not absolute. Sometimes LDA might yield better results due to error cancellation. Also, please make sure to keep pseudopotentials and functionals consistent. Using pseudopotentials generated with the LDA functional in combination with PBE might lead to worse results.
> 3. The computational demand for functionals is related to system size. However, because both LDA and PBE require minimal computation, the difference is not significant. But when considering meta-GGA or hybrid functionals, the computational load will increase significantly.

Thank you for your answer.
