### ISSUE TITLE
Questions about the plane wave base

### ISSUE THREAD

**Issue by yang2022i** [deepmodeling/abacus-develop#4222]
### Details

——————————————————————————————
Three methods are provided for the distribution of reciprocal space plane waves
method1: Distribute according to the size of sticks.
method2: Distribute directly in order
method3: Based on method1, it handles the distribution of dense grids (in file pw_basis_sup.cpp).

We have the following questions
Q1.What is the meaning of dense grid in method3? Is it the points outside the boundary of method1 or some extra points?
Q2.Why does method2 not need to consider negative indexing?

————————————————————————————————
There are also some places where the code seems to be the same

Q3: The distribute_r() function exists for both PW_Basis_Big and PW_Basis, the difference is only a few extra arguments. What does “big” mean here? Does it mean the search range is expanded or there are more points?
Q4：The difference between pw_transform_k.cpp and pw_transform.cpp is that there is only one more support for wavevector k. Can we just take k = 0 in the formula exp i(k+G)r?
That way only one copy of the code has to be written. The other one would just take k = 0 when called.

**Comment by Qianruipku** [comment]
A1: Dense grid and smooth grid are for ultrasoft pseudopotential. They are all balls in G spaces, and the dense is bigger than the smooth. Method3 can make sure that plane waves both existing in the smooth grid and the dense grid are in the same process.

A2: Method 1 ensures that the number of plane waves for each core is roughly the same, while Method 2 ensures that the number of sticks for each core is roughly the same. Method 2 exists to test whether it is better than Method 1. The result is that Method 1 is better, therefore in ABACUS, Method 1 is used and Method 2 is not used.

A3: The class “big” is temporary and ensures that the dimensions of the FFT can be evenly divided by `bx`, `by`, and `bz`. This is a requirement due to the current lattice integrals. In reality, lattice integrals can be done without this requirement, and in that case, this temporary class can be directly removed.

A4: The arrays used by the two functions are also different. Currently, `pw_basis` and `pw_basis_k` are separate; `pw_basis` is used for density, and when performing a transform, it does not require specifying `ik`, while `pw_basis_k` is used for wave functions and requires specifying `ik` when used. Additionally, `pw_basis_k` has more member functions than `pw_basis`, and even if they are merged, it would not reduce the amount of code significantly.
