### ISSUE TITLE
Possibly incorrect trajectory by abacus cell relaxation

### ISSUE THREAD

**Issue by swome** [deepmodeling/abacus-develop#4228]
### Describe the bug

A superhydride system H-Rb-Mg, the STRU is generated by calypso and of course it highly likely to be unphysical. When the structure is optimized to 200GPa, a very close distance (0.29 A) between H-H is found in one frame of the trajectories.is 

### Expected behavior

During optimization, the distance between atoms should be no shorter than a safe distance. (For H, it is 0.72) So that the overall data quality is guaranteed. 

### To Reproduce

See below
[result.zip](https://github.com/deepmodeling/abacus-develop/files/15430762/result.zip)

### Environment

Abacus 3.5.3 on SugonDCU. Details in the uploaded  input and output

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by WHUweiqingzhou** [comment]
It seems that during the cell-relax process, a relatively high target pressure was set, making it possible that the atomic distances are quite close. The issue to be cautious of is that when using a PW basis set for cell-relax, if there is a large discrepancy between the initial and target pressures, the result will have a larger error compared to the result obtained from a new SCF calculation. This problem is common to all PW basis sets, whereas LCAO basis sets would result in smaller errors. The solution is to perform another cell-relax with the converged configuration.
