### ISSUE TITLE
unnecessarily compiled lib in CMake when ENABLE_LCAO is OFF.

### ISSUE THREAD

**Issue by Qianruipku** [deepmodeling/abacus-develop#4354]
### Describe the Code Quality Issue

![image](https://github.com/deepmodeling/abacus-develop/assets/76200646/63b8e5c0-5e6a-4d69-b5fe-24d49643105b)
When we set ENABLE_LCAO to OFF,  we only want abacus_pw.
However, cmake will compile useless lib, such as operator_ks_pw, hcontainer, gint.
In fact, lib hamilt_pwdft includes lib operator_ks_pw.

### Task list for Issue attackers (only for developers)

- [ ] Identify the specific code file or section with the code quality issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified issue.
- [ ] Refactor the code to improve code quality, following the suggested solution.
- [ ] Ensure the refactored code adheres to the project's coding standards.
- [ ] Test the refactored code to ensure it functions as expected.
- [ ] Update any relevant documentation, if necessary.
- [ ] Submit a pull request with the refactored code and a description of the changes made.

**Comment by yizeyi18** [comment]
The build of `hcontainer` should only controlled by `ENABLE_LCAO`(`CMakeLists.txt, line 707`). Had you explicitly set `-DENABLE_LCAO=OFF` while configuring and cleared old temp files before build?

EDIT: Sorry for my judge, clearing old configure files and reconfigure with `-DENABLE_LCAO=OFF` would really lead to building hcontainer and gint. It's strange.

EDIT2: Highly possible because in the commit introducing `ENABLE_LCAO`(fcdcadd), no logic had been added in `source/CMakeLists.txt`. This file controls which `source/*` dirs would be included in compile stage; `CMakeLists.txt` controls link stage only.
