### ISSUE TITLE
Code does not exit even when errors are encountered

### ISSUE THREAD

**Issue by wenfei-li** [deepmodeling/abacus-develop#4480]
### Describe the bug

I have noticed that, if users set init_chg file but do not provide the required charge density files, the program will not report error and exit. Instead, it will continue with density initialized using atomic densities. The user will then get results that are not what they intend to have.
See below for the code responsible for this behaviour.
![image](https://github.com/deepmodeling/abacus-develop/assets/38569667/88c067b0-f601-49c0-a525-dca8f4ffb580)

### Expected behavior

exit the code with error, or at least give users an option to decide what would be the behaviour they want.

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by pxlxingliang** [comment]
The earlier abacus will quit when init_chg=file when reading file failed, but since https://github.com/deepmodeling/abacus-develop/pull/3264, it is changed to use atomic charge if reading file failed.
It seems, abacus should support these two contradictory functions, and I suggest adding a new option `auto` for init_chg, and modify option `file`:
- file: abacus try to read charge from file, and if reading is failed, abacus will warning quit.
- auto: abacus firstly read charge from file, and if reading is filed, abacus will use atomic charge and keep running.
