### ISSUE TITLE
Default value of mixing_gg0 is not suitable for water monomer system

### ISSUE THREAD

**Issue by xuan112358** [deepmodeling/abacus-develop#4524]
### Details

I recently discovered that the default value of mixing_gg0 was changed from 0 to 1 in the commit #3226 @WHUweiqingzhou . This causes the number of steps required for SCF iterative convergence to change from 9 to 25 in the example of calculating a single water molecule using PBE. This example is packaged below.
Does this mean that in some systems, this default value is not suitable?
[github_mixing_gg0.zip](https://github.com/user-attachments/files/16039785/github_mixing_gg0.zip)

### Task list for Issue attackers (only for developers)

- [ ] Reproduce the performance issue on a similar system or environment.
- [ ] Identify the specific section of the code causing the performance issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified performance issue.
- [ ] Implement the chosen solution to address the performance issue.
- [ ] Test the implemented solution to ensure it improves performance without introducing new issues.
- [ ] Optimize the solution if necessary, considering trade-offs between performance and other factors (e.g., code complexity, readability, maintainability).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Merge the improved solution into the main codebase and notify the issue reporter.

**Comment by WHUweiqingzhou** [comment]
@xuan112358,
Yes, the default value is not good for some cases. I prefer let user modify these parameters as one wish since there is no default value which is good for all systems. Kerker precondition is very helpful for metal, but slow converge for some cases as you see.
Different software provide different default setting, like VASP open gg0 defaultly, while QE close it defaultly. If you have better idea, you can discuss here.

**Comment by xuan112358** [comment]
OK，I get it. Thanks for your help!
