### ISSUE TITLE
Use gint_kernel_vlocal() function  with an incorrect list of arguments

### ISSUE THREAD

**Issue by LiuXiaohui123321** [deepmodeling/abacus-develop#4551]
In the code,  the  `gint_kernel_vlocal()`  function is called with arguments list like this,
https://github.com/deepmodeling/abacus-develop/blob/8942b4776c99c2a3982467a365cda7ddf670fb1c/source/module_hamilt_lcao/module_gint/gint.cpp#L350

but the function is defined with arguments list here, 
https://github.com/deepmodeling/abacus-develop/blob/8942b4776c99c2a3982467a365cda7ddf670fb1c/source/module_hamilt_lcao/module_gint/gint.h#L73-L80

As we see, the arguments list above doesn't match the one here, and it looks like it's lack of the` pvpR_reduced` item.

There are several other similar problems in the code,

- https://github.com/deepmodeling/abacus-develop/blob/8942b4776c99c2a3982467a365cda7ddf670fb1c/source/module_hamilt_lcao/module_gint/gint.cpp#L354-L360
- https://github.com/deepmodeling/abacus-develop/blob/8942b4776c99c2a3982467a365cda7ddf670fb1c/source/module_hamilt_lcao/module_gint/gint.cpp#L435-L442
- https://github.com/deepmodeling/abacus-develop/blob/8942b4776c99c2a3982467a365cda7ddf670fb1c/source/module_hamilt_lcao/module_gint/gint.cpp#L446-L453

**Comment by WHUweiqingzhou** [comment]
@dzzz2001 could you have a look?

**Comment by dzzz2001** [comment]
It appears that this error was introduced after adding the `unitcell` parameter in the `gint_kernel_vlocal` function. The correct order of parameters when calling this function should place `nullptr` before `ucell`. Since ABACUS currently lacks compilation tests for non-OpenMP versions, this error was not caught by the integration tests. This is an error introduced by PR #4164, @A-006 you should fix it.

**Comment by A-006** [comment]
This issue has been resolved in the #4566 . If there are no problems, this issue can be closed.
