### ISSUE TITLE
Pre-commit.ci failure due to permission denied

### ISSUE THREAD

**Issue by maki49** [deepmodeling/abacus-develop#4589]
Up to now I find it only happens in @PeizeLin 's PR  (like #4558 and #4590), so I guess it is because his repository is forked from [abacusmodeling ](https://github.com/abacusmodeling/abacus-develop) rather than [deepmodeling](https://github.com/deepmodeling/abacus-develop). This problem should not block the merge.

![image](https://github.com/deepmodeling/abacus-develop/assets/33978601/e70dc59c-df06-44cc-b1c8-850ce7211d65)

**Comment by caic99** [comment]
Hi @maki49 ,
Running pre-commit.ci services requires access to that repo, so your guess is possibly correct. We've asked the user to[ fork the repo](https://github.com/deepmodeling/abacus-develop/blob/develop/docs/CONTRIBUTING.md#submitting-a-pull-request) from the deepmodeling community. And since pre-commit is not an action required to be passed, it is not blocking the merging progress.

**Comment by mohanchen** [comment]
Besides the solution you just provided, there is still an issue remains. Apparently, from the point of code reviewer, any PRs that failed the pre-commit is labelled as 'failed PR', making the reviewer very confusing. What's your suggestion to deal with this situation? @caic99

**Comment by caic99** [comment]
@mohanchen From the view of the person who decides whether to merge that PR, the PR status page shows: 
i. squash and merge, which means the required actions are passed and there is at least 1 approving review, or 
ii. merging is blocked, which the condition above is not satisfied.
I think these info is sufficient for them.

**Comment by caic99** [comment]
@mohanchen Or, the reviewer can request the developer to submit a PR from a repo forked from deepmodeling repo, ensuring the correctness.

**Comment by mohanchen** [comment]
Thanks!
