### ISSUE TITLE
Incorrect electron number when setting 'smearing' to be 'fixed' and symmetry to be '1'

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#464]
## Describe the Bug
When setting 'smearing' to be 'fixed' and symmetry to be '1',  the electron number by summing the value in all k-points is wrong.
[example.zip](https://github.com/deepmodeling/abacus-develop/files/7568809/example.zip)

**Comment by dyzheng** [comment]
The system in "example.zip" belongs to metal and its number of valence electron is odd (1Li+2Sn).
So the system can't use fixed method for evaluating occupied bands, if you try "smearing gauss", result of electron number would be right.
Another problem is the setting of "niter" is 2, which caused convergence have not been achieved.

This issue looks like caused by setting "symmetry 1", but the symmetry analysis is correct for this case.@pxlxingliang

**Comment by pxlxingliang** [comment]
Even though I don't know how the bug is fixed, in the lasted version, the electron number is correct.
