### ISSUE TITLE
Build failed on oneAPI toolchain with deepks and testing ON

### ISSUE THREAD

**Issue by Cstandardlib** [deepmodeling/abacus-develop#4673]
### Describe the bug

When building latest abacus with `-DBUILD_TESTING=ON` and `-DENABLE_DEEPKS=1`, compiler error encountered:
![img_v3_02cn_0c242d2f-d0c0-4933-9580-4b42268cd40g](https://github.com/user-attachments/assets/836fd34a-e7d6-433a-b259-ad62b34ebe44)

### To Reproduce

```zsh
. /opt/intel/oneapi/2024.2/oneapi-vars.sh
echo rm -rf build
rm -rf build
CXX=mpiicpx cmake -B build -DBUILD_TESTING=ON -DENABLE_DEEPKS=1 -DTorch_DIR=~/packages/libtorch/share/cmake/Torch/ -Dlibnpy_INCLUDE_DIR=~/packages/libnpy/include
cmake --build build -j`nproc` && sudo cmake --install build
```

### Environment

- OS: Ubuntu 22.04
- Compiler: IntelLLVM 2024.2.0

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by AsTonyshment** [comment]
I am encountering this issue as well, so it seems to be not an isolated case.

**Comment by kirk0830** [comment]
this is because the following lines in unittest:
https://github.com/deepmodeling/abacus-develop/blob/4879745324ff76d2f05e60c90cc878ce4b68efa2/source/module_esolver/test/esolver_dp_test.cpp#L2-L3

the `#define private public` and `#define protected public` break c++ STL implementation, this is the result of bad design of classes and redandunt tests on even getter functions. The developer of this class did not really design it well, the proper choice should be, once the instance is constructed, its state is determined or say determinstic, then just use getter function to check its state, this is a proper unittest of constructor. Otherwise if want to test some functionalities and if find it is needed to change the state by visiting private variables, it is either not well designed encapsulation or not well designed function, the latter case implies the function should be static instead of dynamic.

Similar problem: https://github.com/deepmodeling/abacus-develop/issues/2666
