### ISSUE TITLE
Add some notes to pw force

### ISSUE THREAD

**Issue by yufengwhy** [deepmodeling/abacus-develop#470]
## Describe Current Status and Possible Solution

https://github.com/deepmodeling/abacus-develop/blob/develop/source/src_pw/forces.cpp

Is there any reference material for force with plane wave? Which can match above code.
1. Why force can be summed via ion, local and nonlocal parts?
2. Is it true that " ion=local+nonlocal "? If so, the ion part are repeated calculated?

**Comment by Qianruipku** [comment]
Reference: Martin, Electronic Structure P182 P256
F=F_ion(or F_ewald)+F_local+F_nonlocal. Local and nonlocal parts derive from the local and nonlocal parts of pseudopotential (See P 255).
F_ion describe the forces between ions, while F_local and F_nonlocal are the forces between electrons and ions.
So ion is not equal to local + nonlocal

**Comment by Qianruipku** [comment]
![图片](https://user-images.githubusercontent.com/76200646/143223008-4df2a15f-df0f-443f-b573-764a6e20a90d.png)

**Comment by Qianruipku** [comment]
![图片](https://user-images.githubusercontent.com/76200646/143223075-92e80712-a5c9-47e7-b355-043fed97b5b4.png)

**Comment by yufengwhy** [comment]
Thanks a lot. Eq. (13.3) gives an explicit form. Is there recommended reference materials for:
1. The [code](https://github.com/deepmodeling/abacus-develop/blob/develop/source/src_pw/forces.cpp) has scc and nlcc terms, representing what?
2. The derivation of Eq. (13.3) ,
2. The derivation of Eq. (13.3) to the c++ [code](https://github.com/deepmodeling/abacus-develop/blob/develop/source/src_pw/forces.cpp)
I had read related sections in Martin, Electronic Structure, but only a few pages, so I wonder if there is richer introductions?

**Comment by Qianruipku** [comment]
NLCC: non-linear core corrections  See P219 and SG Louie, S Froyen, ML Cohen, Physical Review B, 1982 
SCC: contributino due to incomplete SCF calculation. See P183 and C. T. Chan, K. P. Bohnen, and K. M. Ho, Phys. Rev. B 47, 4771
Force is only the derivative of energy about atom's positions. I did not see any detailed derivation. Maybe you can refer to the detailed expression of total energy in Martin's book and deduce it by yourself. It is not hard. : )
Note that the plane wave basis is independent of atom's position. The derivative only results from the structure factor.

**Comment by mohanchen** [comment]
@yufengwhy Hi, I think this topic is not an issue, it is a discussion, I would suggest moving this topic to the github "discussions" panel. Thanks a lot.

**Comment by mohanchen** [comment]
If you have more questions about the basic formulas of DFT, please try to use the "discussions" panel.
