### ISSUE TITLE
Confused about Condon–Shortley phase related problem

### ISSUE THREAD

**Issue by Franklalalala** [deepmodeling/abacus-develop#4908]
### Details

In the [doc of abacus](https://abacus.deepmodeling.com/en/latest/advanced/pp_orb.html), it mentions that, the formula in [wiki](https://en.wikipedia.org/wiki/Table_of_spherical_harmonics#Real_spherical_harmonics) lacks the Condon–Shortley phase, therefore abacus team added the Condon–Shortley phase, and used this form in the lcao orbitals of ABACUS. 

Here are two questions:
1. It has been mentioned in [another wiki](https://en.wikipedia.org/wiki/Spherical_harmonics#Real_form), the real form of spherical harmonics can be infered from the complex form. In emphasis, quote, 'The Condon–Shortley phase convention is used here for consistency.'
Is there a possibility that the real forms of spherical harmonics listed in the first [wiki](https://en.wikipedia.org/wiki/Table_of_spherical_harmonics#Real_spherical_harmonics) do contain the Condon–Shortley phase?

2. Regardless of the correctness of the [wiki](https://en.wikipedia.org/wiki/Table_of_spherical_harmonics#Real_spherical_harmonics) form, does abacus team add another (-1)^m in their lcao orbitals? Since most developers  follow the same form with wiki, such as pyscf, see [doc](https://pyscf.org/user/gto.html#ordering-of-basis-functions). If abacus is different from wiki, we will add (-1)^m for communincation with pyscf. However, as far as I searched, there is no additional consideration for this, except a mention in test scipt. [Here](https://github.com/deepmodeling/abacus-develop/blob/1bea224952196f30fca29634d81dc8e4e019af29/source/module_base/test/math_ylmreal_test.cpp#L19)

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [X] Yes, I have read the FAQ part on online manual.

### Task list for Issue attackers (only for developers)

- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by jinzx10** [comment]
Thanks for your question. Our documentation is indeed somewhat confusing and the relevant section will be revised to clarify this topic in a further PR. To answer your question 2, yes the real spherical harmonics adopted by abacus do differ from those listed in wikipedia by a factor of (-1)^m. To be more precise, real spherical harmonics in abacus takes the following form, in comparison with those in wiki:

![image](https://github.com/user-attachments/assets/dfa58d7b-1860-408c-99f5-5d1525552ecf)
![image](https://github.com/user-attachments/assets/2db4c296-494b-4a8a-9a1d-b2f5aec55854)

where $Y_{lm}$ and $Y_{l}^{m}$ represent real and conventional (complex) spherical harmonics respectively, and the complex spherical harmonics are defined to carry the Condon-Shortley phase. The order of m in abacus follows 0, +1, -1, +2, -2, ..., +l, -l, which is different from pyscf as well.

Question 1 seems to be a terminology issue. To my knowledge, Condon-Shortley phase is introduced to the ***complex*** spherical harmonics in order to simplify the treatment with ladder operators, while the sign convention of real spherical harmonics is a completely different matter motivated by computational consideration. The sign convention adopted in wiki does have an advantage that the resulting functions are signless in Cartesian coordinate (i.e., px/py/pz are simply x/r, y/r, z/r, while in abacus they are -x/r, -y/r, z/r), but I'm not sure if the extra (-1)^m are "Condon-Shortley phase" (in fact they act to cancel the original Condon-Shortley phase in the complex spherical harmonics). I think what wiki means by "The Condon–Shortley phase convention is used here for consistency" is probably that the complex spherical harmonics on the r.h.s. contains the phase, not the real spherical harmonics on the l.h.s. It's possible that I misunderstood wiki and missed some literatures on this terminology; I will appreciate if you could provide your feedback.

The convention adopted by wiki is indeed very popular, but the other convention can also be seen in a number of literatures, e.g., 

Homeier, H. H., & Steinborn, E. O. (1996). Some properties of the coupling coefficients of real spherical harmonics and their relation to Gaunt coefficients. Journal of Molecular Structure: THEOCHEM, 368, 31-37.

Hope this reply helps.

**Comment by Franklalalala** [comment]
Your reply has greatly clearified my confusion. 

I have no question about the difference between abacus and wiki now.

For the terminology, here are some of my understandings to help with the discussion.

1. The complex form of spherical harmonics takes the consideration of the Condon–Shortley phase factor. Once, not twice, with the associated Legendre polynomials takes no Condon–Shortley phase and an explicit form on the forehead.
![image](https://github.com/user-attachments/assets/98a6f2ee-f48c-4ea2-9bf6-5711c33848f9)

2. The real form of spherical harmonics can be infered from the the complex form.
![image](https://github.com/user-attachments/assets/9c97f17a-4af9-4813-8a81-c341bb8543d6)

3. Point is, by obtaining the real form from the complex, the functionality of the (-1)^m used here. Is it the canceling or just follow the convention. Regardless of this point, there are two things we can confirm:

a. The complex form of spherical harmonics contains the Condon–Shortley phase as showed in [wiki](https://en.wikipedia.org/wiki/Spherical_harmonics#Conventions).
b. The real form of spherical harmonics, after transformation, still contains a (-1)^m, we just don't know how to name it. see below:
![image](https://github.com/user-attachments/assets/0610932f-8900-453f-aa2f-d643b68c5c40)

However, as many of the other online forums, [some people](https://physics.stackexchange.com/questions/301688/why-do-we-need-the-condon-shortley-phase-in-spherical-harmonics) take the (-1)^m (b) as Condon–Shortley phase for the real form, which leads to a simplified form as listed in [another wiki](https://en.wikipedia.org/wiki/Table_of_spherical_harmonics#Real_spherical_harmonics). In this way, people conclude that 

"the real form of spherical harmonics listed in the wiki follows the Condon–Shortley convention."

**Comment by jinzx10** [comment]
Thanks for your feedback! I just have one more comment: while the complex spherical harmonics used by physicists almost always contain a Condon-Shortley phase, it still remains the question of whether to put this phase inside or outside the associated Legendre polynomial. In fact, I believe the $P_l^m$ in the equation you posted under Item 3.b already contain the Condon-Shortley phase (which is consistent with the [wiki page of associated Legendre polynomial](https://en.wikipedia.org/wiki/Associated_Legendre_polynomials)), so the hidden one will cancel the explicit one. This can be easily verified by taking $l=1, m=1$.

**Comment by Franklalalala** [comment]
Yes, me and another fellow has found this case 3 hours ago. The associated Legendre polynomial in 3.b indeed contains a phase, as can be verified by [another website](https://mathworld.wolfram.com/AssociatedLegendrePolynomial.html).
<img width="1049" alt="5215b1dd774ace134eb32229367913c" src="https://github.com/user-attachments/assets/56c3cda3-8cd6-4a4e-94ae-292d3d11d453">

I think now we are very much clear about the whole progress, it has been a great pleasure to learn this new concept today. Thank you for your valuable discussion!
