### ISSUE TITLE
energy is hard to converge with nspin=4

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#4992]
### Describe the Testing Issue

I have do the finite difference test of Fe2 with nspin=2 and nspin=4.
For calculations with nspin=2 and nspin=4, the drho is converged to 1e-7, while for nspin=2 the energy can converge to 1e
-7 eV, and for nspin=4 the energy only converge to about 1e-4 eV.

![image](https://github.com/user-attachments/assets/c64d9350-45b8-411a-95fe-eea23df53e8f)

![image](https://github.com/user-attachments/assets/96083f07-011e-4fbf-9457-3d1d90070967)

Job link: https://bohrium.dp.tech/apps/abacustest/job?type=jobs&jobId=25129

### Task list for Issue attackers (only for developers)

- [ ] Understand the testing issue described by the developer.
- [ ] Review the specific test case, expected and actual results, and any error messages.
- [ ] Identify the root cause of the test failure or issue.
- [ ] If a possible solution is suggested, evaluate its feasibility and effectiveness.
- [ ] Implement a fix for the test failure or issue, or create a new test case if needed.
- [ ] Verify that the fix resolves the testing issue and the test case passes.
- [ ] Review and update any relevant documentation, such as test plans or user guides.
- [ ] Ensure the testing issue is resolved and close the ticket.
- [ ] Share any lessons learned or best practices with the team to prevent similar issues in the future.

**Comment by pxlxingliang** [comment]
The outputs:
[fe2.zip](https://github.com/user-attachments/files/16724587/fe2.zip)

**Comment by WHUweiqingzhou** [comment]
I chose the `cell0` to test and changed `scf_thr_type` to 1/2. In the PW calculations, the default real-space mixing of LCAO was used. It was found that the convergence curves of PW and LCAO are similar, and the energy can reach 1e-6 accuracy. A criterion of 1e-7 only resulted in accuracy of 1e-4, which is because, in this system, different scf_thr_type options resulted in drho differences of up to 4 to 5 orders of magnitude. Therefore, in the PW calculations of this system, using drho=1e-10 or lower might be more reasonable; of course, this also depends on the system. If one is more familiar with the drho values defined by LCAO, `scf_thr_type` can be set to 2 in the calculations.

![img_v3_02e7_af5c1ee8-e829-4eff-807e-3a0d173290fg](https://github.com/user-attachments/assets/3310b551-06a8-49b3-803f-6d8f516ba637)
![img_v3_02e7_66e1004d-1d4c-41d4-8c9b-1b0cde7b681g](https://github.com/user-attachments/assets/6dd676da-81f7-4be4-9163-9cfd5dd464b5)
