### ISSUE TITLE
Has symmetry analysis been included in magnetic and/or noncollinear calculations in ABACUS

### ISSUE THREAD

**Issue by hongriTianqi** [deepmodeling/abacus-develop#518]
## Background
The INPUT file tag symmetry is set to 1 in some tests in magnetic and/or noncollinear calculations in ABACUS under the tests/integrate directory (104_PW_AF_magnetic, 104_PW_FM_magnetic, 104_PW_NC_magnetic, 204_NO_KP_AFM, 204_NO_KP_FM ). One will wonder 
whether symmetry analysis has been included in magnetic and/or noncollinear calculations in ABACUS, or not?

**Comment by dyzheng** [comment]
If the time inversion symmetry is added, possibly QE has, may make the antiferromagnet easily converge.
We now practice that atoms of different magnetic moments are treated by different elements so that symmetry=1 can be opened. But initialization by the atomic magnetic moment can lead to a symmetry search error.
