### ISSUE TITLE
No ELF.cube output for SOC calculations

### ISSUE THREAD

**Issue by 1041176461** [deepmodeling/abacus-develop#5394]
### Describe the bug

I set `out_elf   1` in INPUT with ABACUS develop version, however, there is no ELF.cube file under OUT.ABACUS. Here is my INPUT files
![Image](https://github.com/user-attachments/assets/bd36b300-3411-4c2f-8224-f760d4742371)
 The job finished successfully
![Image](https://github.com/user-attachments/assets/bd86667b-77be-4c9b-993e-48ed029b54fa)

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by 1041176461** [comment]
@mohanchen @sunliang98 Can this problem be solved first? I need to add some ELF data recently. Thanks!

**Comment by sunliang98** [comment]
In this case, with the SOC being activated, the parameter `nspin` is set to 4 by default. However, at present, the implementation of the Electron Localization Function (ELF) for `nspin = 4` is not supported due to the following limitations:

1. Definitions of the ELF for individual electron spins have been established for cases where `nspin = 2` and `1` (see [out_elf](https://abacus.deepmodeling.com/en/latest/advanced/input_files/input-main.html#out-elf)) but no equivalent has been defined for `nspin = 4`.
2. Additionally, the total ELF for `nspin = 4` is unavailable as the ABACUS does not currently support the calculation of the kinetic energy density tau for such a setting.

**Comment by 1041176461** [comment]
@sunliang98 Got it. Thanks!
