### ISSUE TITLE
Bug: ABACUS requires 1.75922e+13 MB memory on some machine when setting ecutwfc 2000 Ry

### ISSUE THREAD

**Issue by kirk0830** [deepmodeling/abacus-develop#5538]
### Describe the bug

[ecutwfc2000Ry.zip](https://github.com/user-attachments/files/17824541/ecutwfc2000Ry.zip)

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by jinzx10** [comment]
It turns out to be an issue of int overflow. The following boxed code (as well as several other places doing the similar calculation)

![Image](https://github.com/user-attachments/assets/e28c6f95-51b0-47a8-865a-3fb4111cbcbf)

may not work as expected, because nks2, nbands, npol & npwx all have type int, whose maximum value is 2^31-1 = 2147483647 on a machine with int defaulted to int32. Although the last term, sizeof(...) will return a size_t, given the evaluation of such arithmetic expression is left-to-right, it will not promote int to size_t until the last multiplication. That is, if the product nks2 * nbands * npol * npwx exceeds INT_MAX, the result would be wrong.

A quick solution is to move sizeof(...) to the first term in the chained multiplication.
