### ISSUE TITLE
Atomic position is not yet considered in symmetry analysis in ABACUS

### ISSUE THREAD

**Issue by hongriTianqi** [deepmodeling/abacus-develop#562]
## Describe the Bug
MgO is fcc, but when we use ABACUS to search its symmetry automatically, ABACUS gives simple cubic. Therefore, it seems that atomic position is not considered in symmetry analysis in ABACUS

## To Reproduce
cat MgO/OUT.MgO/runnning_scf.log

[MgO.tar.gz](https://github.com/deepmodeling/abacus-develop/files/7702678/MgO.tar.gz)

**Comment by hongriTianqi** [comment]
The instructions given by Dr. Xiaohui to solve ISSUE #495 do not solve this issue.

**Comment by dyzheng** [comment]
As far as know, Dr. Pengfei Li is working for solving this problem.
He found that reason for this error caused by your structure is not the best primitive cell for this material. 
ABACUS found the best cell but used new rotation matrix to handle original structure.
We can wait for Dr. Li updating progress.

**Comment by dyzheng** [comment]
MgO is fcc but the case in "MgO.tar.gz" is actual simple cubic.
Simple cubic has higher symmetry than fcc, so the symmetry analysis is not wrong.
