### ISSUE TITLE
Unified output formats and files of the MD function needed

### ISSUE THREAD

**Issue by wenfei-li** [deepmodeling/abacus-develop#609]
Geometries from MD calculations was provided as .cif file. This is no longer available after the reconstruction of MD module. Instead they are provided as STRU file format.
This is causing troubles since the analysis toolkit I have (which was provided by @dyzheng) only deals with .cif file. As a result, would like to have 1) either a script which converts between the two output formats; 2) or an option in the new MD code which allows the old output format.
This might be a common scenario for users of ABACUS, who do not want to switch to new output formats due to various reasons. Also, the .cif format is much more commonly used than the STRU file format which is only used in ABACUS, so why not keep it as an option?

**Comment by mohanchen** [comment]
@YuLiu98 Please describe your full MD output formats here, and we will discuss the solutions for those users using the old output format. @Liu-RX can also provide comments.

**Comment by YuLiu98** [comment]
1) ABACUS must output STRU because it is one input file of ABACUS;
2) cif files even other formats such as POSCAR could be one of output formats,  but I think that converting STRU to other formats (cif, POSCAR and so on) with post-processing tools (such as dpdata ? @Liu-RX) may be a better choice, otherwise we need to provide too many options.
3) MD informations (lattice, positions, forces, virial) of each MD step are contained in `MD_dump` file in the latest version, so that all information needed by MD analysis can be accessed through a single file.

**Comment by Liu-RX** [comment]
We have an analysis toolkit available for the latest format. I will send the toolkit to you @wenfei-li . If the output format is the finally settled version, I will adapt it to dpdata in the following days.

**Comment by Liu-RX** [comment]
Furthermore, although the MD output format is still unsettled, I don’t think we should use the old cif format any longer. The cif format requires coordinate transformation before output, sometimes making the output and input structure in two different coordinates. This will be big trouble in NpT ensemble since the simulation box keeps changing and you will be unable to trace a, b or c vector with the cif files. If the cif file is still needed, I will write a cif interface in dpdata for format transformation.
