### ISSUE TITLE
Serial version of ABACUS needs refactor

### ISSUE THREAD

**Issue by lyb9812** [deepmodeling/abacus-develop#709]
## Describe the Bug
When I compile the serial version, a lot of codes corresponding to MPI  are still compiled, and some functions for the serial version are not correct.

## To Reproduce
1. change $HONG in Makefile to serial version
2. make fp

## Environment
- OS: ubuntu 18.04
- Compiler: OneAPI 2021.3.0

**Comment by lyb9812** [comment]
I cannot change the assignees on my computer.

**Comment by mohanchen** [comment]
please also pay attention to 
https://github.com/deepmodeling/abacus-develop/issues/771

**Comment by mohanchen** [comment]
please also pay attention to 
https://github.com/deepmodeling/abacus-develop/issues/771

**Comment by mohanchen** [comment]
please also pay attention to 
https://github.com/deepmodeling/abacus-develop/issues/771

**Comment by hongriTianqi** [comment]
- [ ] Identify the specific code file or section with the code quality issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified issue.
- [ ] Refactor the code to improve code quality, following the suggested solution.
- [ ] Ensure the refactored code adheres to the project's coding standards.
- [ ] Test the refactored code to ensure it functions as expected.
- [ ] Update any relevant documentation, if necessary.
- [ ] Submit a pull request with the refactored code and a description of the changes made.

**Comment by mohanchen** [comment]
This will be done in an appropriate time.
