### ISSUE TITLE
Bug for 107_PW_OD_outputdos

### ISSUE THREAD

**Issue by Qianruipku** [deepmodeling/abacus-develop#746]
## Describe the Bug
Sometime, 107_PW_OD_outputdos cannot pass the autotest

## To Reproduce
0. Download develop branch
1. Compile it with Makefile
2. Test 107_PW_OD_outputdos
3. Repeat  until it shows ERROR: 
Sometimes it is OK:
![图片](https://user-images.githubusercontent.com/76200646/155482527-1f46d9e9-920d-49d8-94a6-a17f3408557e.png)
sometimes it is wrong:
![图片](https://user-images.githubusercontent.com/76200646/155482221-785ab516-4ed1-4421-8259-a820f8dd79d2.png)
[result.txt](https://github.com/deepmodeling/abacus-develop/files/8130648/result.txt)

## Environment
- OS: Ubuntu16.04
- Compiler: oneapi2021
- Optional Dependencies: [e.g. Intel MKL]

**Comment by Qianruipku** [comment]
Compiling it with cmake will also repeat it.

**Comment by caic99** [comment]
Hi @Qianruipku ,
Similar cases have appeard before, see #637 .

**Comment by wenfei-li** [comment]
The reason behind this bug is that in calculating DOS_smearing, the program first takes the calculated DOS as input:
```
			 for(int i=0;i<number;i++)
			 {
				 in >> energy[i] >> dos[i];
			 }
			 if(!in.eof())
			 {
				 //std::cout<<"\n Read Over!"<<std::endl;
			 }
			 in.close();
```
This might have something to do with the input buffer. Also, it is bad practice to use the output file of the program as input file.
The way to fix this is to save the array that stores DOS and use that in calculating DOS_smearing, instead of reading from DOS.
